// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_transport.proto

package com.zhaoyan.communication.protocol.pb;

public final class PBFileTransportProtos {
  private PBFileTransportProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PBSendFileOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 sendUserId = 1;
    /**
     * <code>required int32 sendUserId = 1;</code>
     */
    boolean hasSendUserId();
    /**
     * <code>required int32 sendUserId = 1;</code>
     */
    int getSendUserId();

    // required int32 recieveUserId = 2;
    /**
     * <code>required int32 recieveUserId = 2;</code>
     */
    boolean hasRecieveUserId();
    /**
     * <code>required int32 recieveUserId = 2;</code>
     */
    int getRecieveUserId();

    // required int32 appId = 3;
    /**
     * <code>required int32 appId = 3;</code>
     */
    boolean hasAppId();
    /**
     * <code>required int32 appId = 3;</code>
     */
    int getAppId();

    // optional bytes serverAddress = 4;
    /**
     * <code>optional bytes serverAddress = 4;</code>
     */
    boolean hasServerAddress();
    /**
     * <code>optional bytes serverAddress = 4;</code>
     */
    com.google.protobuf.ByteString getServerAddress();

    // optional int32 serverPort = 5;
    /**
     * <code>optional int32 serverPort = 5;</code>
     */
    boolean hasServerPort();
    /**
     * <code>optional int32 serverPort = 5;</code>
     */
    int getServerPort();

    // optional .com.zhaoyan.juyou.PBFileInfo fileInfo = 6;
    /**
     * <code>optional .com.zhaoyan.juyou.PBFileInfo fileInfo = 6;</code>
     */
    boolean hasFileInfo();
    /**
     * <code>optional .com.zhaoyan.juyou.PBFileInfo fileInfo = 6;</code>
     */
    com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo getFileInfo();
    /**
     * <code>optional .com.zhaoyan.juyou.PBFileInfo fileInfo = 6;</code>
     */
    com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfoOrBuilder getFileInfoOrBuilder();
  }
  /**
   * Protobuf type {@code com.zhaoyan.juyou.PBSendFile}
   */
  public static final class PBSendFile extends
      com.google.protobuf.GeneratedMessage
      implements PBSendFileOrBuilder {
    // Use PBSendFile.newBuilder() to construct.
    private PBSendFile(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PBSendFile(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PBSendFile defaultInstance;
    public static PBSendFile getDefaultInstance() {
      return defaultInstance;
    }

    public PBSendFile getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PBSendFile(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              sendUserId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              recieveUserId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              appId_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              serverAddress_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              serverPort_ = input.readInt32();
              break;
            }
            case 50: {
              com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000020) == 0x00000020)) {
                subBuilder = fileInfo_.toBuilder();
              }
              fileInfo_ = input.readMessage(com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(fileInfo_);
                fileInfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000020;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.internal_static_com_zhaoyan_juyou_PBSendFile_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.internal_static_com_zhaoyan_juyou_PBSendFile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBSendFile.class, com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBSendFile.Builder.class);
    }

    public static com.google.protobuf.Parser<PBSendFile> PARSER =
        new com.google.protobuf.AbstractParser<PBSendFile>() {
      public PBSendFile parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBSendFile(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PBSendFile> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 sendUserId = 1;
    public static final int SENDUSERID_FIELD_NUMBER = 1;
    private int sendUserId_;
    /**
     * <code>required int32 sendUserId = 1;</code>
     */
    public boolean hasSendUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 sendUserId = 1;</code>
     */
    public int getSendUserId() {
      return sendUserId_;
    }

    // required int32 recieveUserId = 2;
    public static final int RECIEVEUSERID_FIELD_NUMBER = 2;
    private int recieveUserId_;
    /**
     * <code>required int32 recieveUserId = 2;</code>
     */
    public boolean hasRecieveUserId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 recieveUserId = 2;</code>
     */
    public int getRecieveUserId() {
      return recieveUserId_;
    }

    // required int32 appId = 3;
    public static final int APPID_FIELD_NUMBER = 3;
    private int appId_;
    /**
     * <code>required int32 appId = 3;</code>
     */
    public boolean hasAppId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 appId = 3;</code>
     */
    public int getAppId() {
      return appId_;
    }

    // optional bytes serverAddress = 4;
    public static final int SERVERADDRESS_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString serverAddress_;
    /**
     * <code>optional bytes serverAddress = 4;</code>
     */
    public boolean hasServerAddress() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes serverAddress = 4;</code>
     */
    public com.google.protobuf.ByteString getServerAddress() {
      return serverAddress_;
    }

    // optional int32 serverPort = 5;
    public static final int SERVERPORT_FIELD_NUMBER = 5;
    private int serverPort_;
    /**
     * <code>optional int32 serverPort = 5;</code>
     */
    public boolean hasServerPort() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 serverPort = 5;</code>
     */
    public int getServerPort() {
      return serverPort_;
    }

    // optional .com.zhaoyan.juyou.PBFileInfo fileInfo = 6;
    public static final int FILEINFO_FIELD_NUMBER = 6;
    private com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo fileInfo_;
    /**
     * <code>optional .com.zhaoyan.juyou.PBFileInfo fileInfo = 6;</code>
     */
    public boolean hasFileInfo() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .com.zhaoyan.juyou.PBFileInfo fileInfo = 6;</code>
     */
    public com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo getFileInfo() {
      return fileInfo_;
    }
    /**
     * <code>optional .com.zhaoyan.juyou.PBFileInfo fileInfo = 6;</code>
     */
    public com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfoOrBuilder getFileInfoOrBuilder() {
      return fileInfo_;
    }

    private void initFields() {
      sendUserId_ = 0;
      recieveUserId_ = 0;
      appId_ = 0;
      serverAddress_ = com.google.protobuf.ByteString.EMPTY;
      serverPort_ = 0;
      fileInfo_ = com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSendUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRecieveUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAppId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasFileInfo()) {
        if (!getFileInfo().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, sendUserId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, recieveUserId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, appId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, serverAddress_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, serverPort_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeMessage(6, fileInfo_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sendUserId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, recieveUserId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, appId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, serverAddress_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, serverPort_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, fileInfo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBSendFile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBSendFile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBSendFile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBSendFile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBSendFile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBSendFile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBSendFile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBSendFile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBSendFile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBSendFile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBSendFile prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zhaoyan.juyou.PBSendFile}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBSendFileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.internal_static_com_zhaoyan_juyou_PBSendFile_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.internal_static_com_zhaoyan_juyou_PBSendFile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBSendFile.class, com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBSendFile.Builder.class);
      }

      // Construct using com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBSendFile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFileInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sendUserId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        recieveUserId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        appId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        serverAddress_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        serverPort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        if (fileInfoBuilder_ == null) {
          fileInfo_ = com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo.getDefaultInstance();
        } else {
          fileInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.internal_static_com_zhaoyan_juyou_PBSendFile_descriptor;
      }

      public com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBSendFile getDefaultInstanceForType() {
        return com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBSendFile.getDefaultInstance();
      }

      public com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBSendFile build() {
        com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBSendFile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBSendFile buildPartial() {
        com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBSendFile result = new com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBSendFile(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sendUserId_ = sendUserId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.recieveUserId_ = recieveUserId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.appId_ = appId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.serverAddress_ = serverAddress_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.serverPort_ = serverPort_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        if (fileInfoBuilder_ == null) {
          result.fileInfo_ = fileInfo_;
        } else {
          result.fileInfo_ = fileInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBSendFile) {
          return mergeFrom((com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBSendFile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBSendFile other) {
        if (other == com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBSendFile.getDefaultInstance()) return this;
        if (other.hasSendUserId()) {
          setSendUserId(other.getSendUserId());
        }
        if (other.hasRecieveUserId()) {
          setRecieveUserId(other.getRecieveUserId());
        }
        if (other.hasAppId()) {
          setAppId(other.getAppId());
        }
        if (other.hasServerAddress()) {
          setServerAddress(other.getServerAddress());
        }
        if (other.hasServerPort()) {
          setServerPort(other.getServerPort());
        }
        if (other.hasFileInfo()) {
          mergeFileInfo(other.getFileInfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSendUserId()) {
          
          return false;
        }
        if (!hasRecieveUserId()) {
          
          return false;
        }
        if (!hasAppId()) {
          
          return false;
        }
        if (hasFileInfo()) {
          if (!getFileInfo().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBSendFile parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBSendFile) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 sendUserId = 1;
      private int sendUserId_ ;
      /**
       * <code>required int32 sendUserId = 1;</code>
       */
      public boolean hasSendUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 sendUserId = 1;</code>
       */
      public int getSendUserId() {
        return sendUserId_;
      }
      /**
       * <code>required int32 sendUserId = 1;</code>
       */
      public Builder setSendUserId(int value) {
        bitField0_ |= 0x00000001;
        sendUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 sendUserId = 1;</code>
       */
      public Builder clearSendUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sendUserId_ = 0;
        onChanged();
        return this;
      }

      // required int32 recieveUserId = 2;
      private int recieveUserId_ ;
      /**
       * <code>required int32 recieveUserId = 2;</code>
       */
      public boolean hasRecieveUserId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 recieveUserId = 2;</code>
       */
      public int getRecieveUserId() {
        return recieveUserId_;
      }
      /**
       * <code>required int32 recieveUserId = 2;</code>
       */
      public Builder setRecieveUserId(int value) {
        bitField0_ |= 0x00000002;
        recieveUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 recieveUserId = 2;</code>
       */
      public Builder clearRecieveUserId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        recieveUserId_ = 0;
        onChanged();
        return this;
      }

      // required int32 appId = 3;
      private int appId_ ;
      /**
       * <code>required int32 appId = 3;</code>
       */
      public boolean hasAppId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 appId = 3;</code>
       */
      public int getAppId() {
        return appId_;
      }
      /**
       * <code>required int32 appId = 3;</code>
       */
      public Builder setAppId(int value) {
        bitField0_ |= 0x00000004;
        appId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 appId = 3;</code>
       */
      public Builder clearAppId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        appId_ = 0;
        onChanged();
        return this;
      }

      // optional bytes serverAddress = 4;
      private com.google.protobuf.ByteString serverAddress_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes serverAddress = 4;</code>
       */
      public boolean hasServerAddress() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes serverAddress = 4;</code>
       */
      public com.google.protobuf.ByteString getServerAddress() {
        return serverAddress_;
      }
      /**
       * <code>optional bytes serverAddress = 4;</code>
       */
      public Builder setServerAddress(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        serverAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes serverAddress = 4;</code>
       */
      public Builder clearServerAddress() {
        bitField0_ = (bitField0_ & ~0x00000008);
        serverAddress_ = getDefaultInstance().getServerAddress();
        onChanged();
        return this;
      }

      // optional int32 serverPort = 5;
      private int serverPort_ ;
      /**
       * <code>optional int32 serverPort = 5;</code>
       */
      public boolean hasServerPort() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 serverPort = 5;</code>
       */
      public int getServerPort() {
        return serverPort_;
      }
      /**
       * <code>optional int32 serverPort = 5;</code>
       */
      public Builder setServerPort(int value) {
        bitField0_ |= 0x00000010;
        serverPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 serverPort = 5;</code>
       */
      public Builder clearServerPort() {
        bitField0_ = (bitField0_ & ~0x00000010);
        serverPort_ = 0;
        onChanged();
        return this;
      }

      // optional .com.zhaoyan.juyou.PBFileInfo fileInfo = 6;
      private com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo fileInfo_ = com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo, com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo.Builder, com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfoOrBuilder> fileInfoBuilder_;
      /**
       * <code>optional .com.zhaoyan.juyou.PBFileInfo fileInfo = 6;</code>
       */
      public boolean hasFileInfo() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .com.zhaoyan.juyou.PBFileInfo fileInfo = 6;</code>
       */
      public com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo getFileInfo() {
        if (fileInfoBuilder_ == null) {
          return fileInfo_;
        } else {
          return fileInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.zhaoyan.juyou.PBFileInfo fileInfo = 6;</code>
       */
      public Builder setFileInfo(com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo value) {
        if (fileInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fileInfo_ = value;
          onChanged();
        } else {
          fileInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .com.zhaoyan.juyou.PBFileInfo fileInfo = 6;</code>
       */
      public Builder setFileInfo(
          com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo.Builder builderForValue) {
        if (fileInfoBuilder_ == null) {
          fileInfo_ = builderForValue.build();
          onChanged();
        } else {
          fileInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .com.zhaoyan.juyou.PBFileInfo fileInfo = 6;</code>
       */
      public Builder mergeFileInfo(com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo value) {
        if (fileInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020) &&
              fileInfo_ != com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo.getDefaultInstance()) {
            fileInfo_ =
              com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo.newBuilder(fileInfo_).mergeFrom(value).buildPartial();
          } else {
            fileInfo_ = value;
          }
          onChanged();
        } else {
          fileInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .com.zhaoyan.juyou.PBFileInfo fileInfo = 6;</code>
       */
      public Builder clearFileInfo() {
        if (fileInfoBuilder_ == null) {
          fileInfo_ = com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo.getDefaultInstance();
          onChanged();
        } else {
          fileInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      /**
       * <code>optional .com.zhaoyan.juyou.PBFileInfo fileInfo = 6;</code>
       */
      public com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo.Builder getFileInfoBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getFileInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.zhaoyan.juyou.PBFileInfo fileInfo = 6;</code>
       */
      public com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfoOrBuilder getFileInfoOrBuilder() {
        if (fileInfoBuilder_ != null) {
          return fileInfoBuilder_.getMessageOrBuilder();
        } else {
          return fileInfo_;
        }
      }
      /**
       * <code>optional .com.zhaoyan.juyou.PBFileInfo fileInfo = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo, com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo.Builder, com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfoOrBuilder> 
          getFileInfoFieldBuilder() {
        if (fileInfoBuilder_ == null) {
          fileInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo, com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo.Builder, com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfoOrBuilder>(
                  fileInfo_,
                  getParentForChildren(),
                  isClean());
          fileInfo_ = null;
        }
        return fileInfoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.zhaoyan.juyou.PBSendFile)
    }

    static {
      defaultInstance = new PBSendFile(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.zhaoyan.juyou.PBSendFile)
  }

  public interface PBFileInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string filePath = 1;
    /**
     * <code>required string filePath = 1;</code>
     */
    boolean hasFilePath();
    /**
     * <code>required string filePath = 1;</code>
     */
    java.lang.String getFilePath();
    /**
     * <code>required string filePath = 1;</code>
     */
    com.google.protobuf.ByteString
        getFilePathBytes();

    // required string fileName = 2;
    /**
     * <code>required string fileName = 2;</code>
     */
    boolean hasFileName();
    /**
     * <code>required string fileName = 2;</code>
     */
    java.lang.String getFileName();
    /**
     * <code>required string fileName = 2;</code>
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    // required int64 fileSize = 3;
    /**
     * <code>required int64 fileSize = 3;</code>
     */
    boolean hasFileSize();
    /**
     * <code>required int64 fileSize = 3;</code>
     */
    long getFileSize();

    // optional bytes fileIcon = 4;
    /**
     * <code>optional bytes fileIcon = 4;</code>
     */
    boolean hasFileIcon();
    /**
     * <code>optional bytes fileIcon = 4;</code>
     */
    com.google.protobuf.ByteString getFileIcon();
  }
  /**
   * Protobuf type {@code com.zhaoyan.juyou.PBFileInfo}
   */
  public static final class PBFileInfo extends
      com.google.protobuf.GeneratedMessage
      implements PBFileInfoOrBuilder {
    // Use PBFileInfo.newBuilder() to construct.
    private PBFileInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PBFileInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PBFileInfo defaultInstance;
    public static PBFileInfo getDefaultInstance() {
      return defaultInstance;
    }

    public PBFileInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PBFileInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              filePath_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              fileName_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              fileSize_ = input.readInt64();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              fileIcon_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.internal_static_com_zhaoyan_juyou_PBFileInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.internal_static_com_zhaoyan_juyou_PBFileInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo.class, com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<PBFileInfo> PARSER =
        new com.google.protobuf.AbstractParser<PBFileInfo>() {
      public PBFileInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBFileInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PBFileInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string filePath = 1;
    public static final int FILEPATH_FIELD_NUMBER = 1;
    private java.lang.Object filePath_;
    /**
     * <code>required string filePath = 1;</code>
     */
    public boolean hasFilePath() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string filePath = 1;</code>
     */
    public java.lang.String getFilePath() {
      java.lang.Object ref = filePath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          filePath_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string filePath = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFilePathBytes() {
      java.lang.Object ref = filePath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string fileName = 2;
    public static final int FILENAME_FIELD_NUMBER = 2;
    private java.lang.Object fileName_;
    /**
     * <code>required string fileName = 2;</code>
     */
    public boolean hasFileName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string fileName = 2;</code>
     */
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fileName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string fileName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int64 fileSize = 3;
    public static final int FILESIZE_FIELD_NUMBER = 3;
    private long fileSize_;
    /**
     * <code>required int64 fileSize = 3;</code>
     */
    public boolean hasFileSize() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 fileSize = 3;</code>
     */
    public long getFileSize() {
      return fileSize_;
    }

    // optional bytes fileIcon = 4;
    public static final int FILEICON_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString fileIcon_;
    /**
     * <code>optional bytes fileIcon = 4;</code>
     */
    public boolean hasFileIcon() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes fileIcon = 4;</code>
     */
    public com.google.protobuf.ByteString getFileIcon() {
      return fileIcon_;
    }

    private void initFields() {
      filePath_ = "";
      fileName_ = "";
      fileSize_ = 0L;
      fileIcon_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasFilePath()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFileName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFileSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFilePathBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getFileNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, fileSize_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, fileIcon_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFilePathBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getFileNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, fileSize_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, fileIcon_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zhaoyan.juyou.PBFileInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.internal_static_com_zhaoyan_juyou_PBFileInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.internal_static_com_zhaoyan_juyou_PBFileInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo.class, com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo.Builder.class);
      }

      // Construct using com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        filePath_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        fileName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        fileSize_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        fileIcon_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.internal_static_com_zhaoyan_juyou_PBFileInfo_descriptor;
      }

      public com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo getDefaultInstanceForType() {
        return com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo.getDefaultInstance();
      }

      public com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo build() {
        com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo buildPartial() {
        com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo result = new com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.filePath_ = filePath_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.fileName_ = fileName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.fileSize_ = fileSize_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.fileIcon_ = fileIcon_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo) {
          return mergeFrom((com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo other) {
        if (other == com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo.getDefaultInstance()) return this;
        if (other.hasFilePath()) {
          bitField0_ |= 0x00000001;
          filePath_ = other.filePath_;
          onChanged();
        }
        if (other.hasFileName()) {
          bitField0_ |= 0x00000002;
          fileName_ = other.fileName_;
          onChanged();
        }
        if (other.hasFileSize()) {
          setFileSize(other.getFileSize());
        }
        if (other.hasFileIcon()) {
          setFileIcon(other.getFileIcon());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFilePath()) {
          
          return false;
        }
        if (!hasFileName()) {
          
          return false;
        }
        if (!hasFileSize()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBFileInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string filePath = 1;
      private java.lang.Object filePath_ = "";
      /**
       * <code>required string filePath = 1;</code>
       */
      public boolean hasFilePath() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string filePath = 1;</code>
       */
      public java.lang.String getFilePath() {
        java.lang.Object ref = filePath_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          filePath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string filePath = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFilePathBytes() {
        java.lang.Object ref = filePath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          filePath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string filePath = 1;</code>
       */
      public Builder setFilePath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        filePath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string filePath = 1;</code>
       */
      public Builder clearFilePath() {
        bitField0_ = (bitField0_ & ~0x00000001);
        filePath_ = getDefaultInstance().getFilePath();
        onChanged();
        return this;
      }
      /**
       * <code>required string filePath = 1;</code>
       */
      public Builder setFilePathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        filePath_ = value;
        onChanged();
        return this;
      }

      // required string fileName = 2;
      private java.lang.Object fileName_ = "";
      /**
       * <code>required string fileName = 2;</code>
       */
      public boolean hasFileName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string fileName = 2;</code>
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string fileName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string fileName = 2;</code>
       */
      public Builder setFileName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        fileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string fileName = 2;</code>
       */
      public Builder clearFileName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      /**
       * <code>required string fileName = 2;</code>
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        fileName_ = value;
        onChanged();
        return this;
      }

      // required int64 fileSize = 3;
      private long fileSize_ ;
      /**
       * <code>required int64 fileSize = 3;</code>
       */
      public boolean hasFileSize() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 fileSize = 3;</code>
       */
      public long getFileSize() {
        return fileSize_;
      }
      /**
       * <code>required int64 fileSize = 3;</code>
       */
      public Builder setFileSize(long value) {
        bitField0_ |= 0x00000004;
        fileSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 fileSize = 3;</code>
       */
      public Builder clearFileSize() {
        bitField0_ = (bitField0_ & ~0x00000004);
        fileSize_ = 0L;
        onChanged();
        return this;
      }

      // optional bytes fileIcon = 4;
      private com.google.protobuf.ByteString fileIcon_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes fileIcon = 4;</code>
       */
      public boolean hasFileIcon() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes fileIcon = 4;</code>
       */
      public com.google.protobuf.ByteString getFileIcon() {
        return fileIcon_;
      }
      /**
       * <code>optional bytes fileIcon = 4;</code>
       */
      public Builder setFileIcon(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        fileIcon_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes fileIcon = 4;</code>
       */
      public Builder clearFileIcon() {
        bitField0_ = (bitField0_ & ~0x00000008);
        fileIcon_ = getDefaultInstance().getFileIcon();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.zhaoyan.juyou.PBFileInfo)
    }

    static {
      defaultInstance = new PBFileInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.zhaoyan.juyou.PBFileInfo)
  }

  public interface PBCancelSendFileOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 receiveUserId = 1;
    /**
     * <code>required int32 receiveUserId = 1;</code>
     */
    boolean hasReceiveUserId();
    /**
     * <code>required int32 receiveUserId = 1;</code>
     */
    int getReceiveUserId();
  }
  /**
   * Protobuf type {@code com.zhaoyan.juyou.PBCancelSendFile}
   */
  public static final class PBCancelSendFile extends
      com.google.protobuf.GeneratedMessage
      implements PBCancelSendFileOrBuilder {
    // Use PBCancelSendFile.newBuilder() to construct.
    private PBCancelSendFile(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PBCancelSendFile(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PBCancelSendFile defaultInstance;
    public static PBCancelSendFile getDefaultInstance() {
      return defaultInstance;
    }

    public PBCancelSendFile getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PBCancelSendFile(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              receiveUserId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.internal_static_com_zhaoyan_juyou_PBCancelSendFile_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.internal_static_com_zhaoyan_juyou_PBCancelSendFile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelSendFile.class, com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelSendFile.Builder.class);
    }

    public static com.google.protobuf.Parser<PBCancelSendFile> PARSER =
        new com.google.protobuf.AbstractParser<PBCancelSendFile>() {
      public PBCancelSendFile parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBCancelSendFile(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PBCancelSendFile> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 receiveUserId = 1;
    public static final int RECEIVEUSERID_FIELD_NUMBER = 1;
    private int receiveUserId_;
    /**
     * <code>required int32 receiveUserId = 1;</code>
     */
    public boolean hasReceiveUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 receiveUserId = 1;</code>
     */
    public int getReceiveUserId() {
      return receiveUserId_;
    }

    private void initFields() {
      receiveUserId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasReceiveUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, receiveUserId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, receiveUserId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelSendFile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelSendFile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelSendFile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelSendFile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelSendFile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelSendFile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelSendFile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelSendFile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelSendFile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelSendFile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelSendFile prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zhaoyan.juyou.PBCancelSendFile}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelSendFileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.internal_static_com_zhaoyan_juyou_PBCancelSendFile_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.internal_static_com_zhaoyan_juyou_PBCancelSendFile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelSendFile.class, com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelSendFile.Builder.class);
      }

      // Construct using com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelSendFile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        receiveUserId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.internal_static_com_zhaoyan_juyou_PBCancelSendFile_descriptor;
      }

      public com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelSendFile getDefaultInstanceForType() {
        return com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelSendFile.getDefaultInstance();
      }

      public com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelSendFile build() {
        com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelSendFile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelSendFile buildPartial() {
        com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelSendFile result = new com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelSendFile(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.receiveUserId_ = receiveUserId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelSendFile) {
          return mergeFrom((com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelSendFile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelSendFile other) {
        if (other == com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelSendFile.getDefaultInstance()) return this;
        if (other.hasReceiveUserId()) {
          setReceiveUserId(other.getReceiveUserId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasReceiveUserId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelSendFile parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelSendFile) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 receiveUserId = 1;
      private int receiveUserId_ ;
      /**
       * <code>required int32 receiveUserId = 1;</code>
       */
      public boolean hasReceiveUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 receiveUserId = 1;</code>
       */
      public int getReceiveUserId() {
        return receiveUserId_;
      }
      /**
       * <code>required int32 receiveUserId = 1;</code>
       */
      public Builder setReceiveUserId(int value) {
        bitField0_ |= 0x00000001;
        receiveUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 receiveUserId = 1;</code>
       */
      public Builder clearReceiveUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        receiveUserId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.zhaoyan.juyou.PBCancelSendFile)
    }

    static {
      defaultInstance = new PBCancelSendFile(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.zhaoyan.juyou.PBCancelSendFile)
  }

  public interface PBCancelReceiveFileOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 sendUserId = 1;
    /**
     * <code>required int32 sendUserId = 1;</code>
     */
    boolean hasSendUserId();
    /**
     * <code>required int32 sendUserId = 1;</code>
     */
    int getSendUserId();
  }
  /**
   * Protobuf type {@code com.zhaoyan.juyou.PBCancelReceiveFile}
   */
  public static final class PBCancelReceiveFile extends
      com.google.protobuf.GeneratedMessage
      implements PBCancelReceiveFileOrBuilder {
    // Use PBCancelReceiveFile.newBuilder() to construct.
    private PBCancelReceiveFile(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PBCancelReceiveFile(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PBCancelReceiveFile defaultInstance;
    public static PBCancelReceiveFile getDefaultInstance() {
      return defaultInstance;
    }

    public PBCancelReceiveFile getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PBCancelReceiveFile(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              sendUserId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.internal_static_com_zhaoyan_juyou_PBCancelReceiveFile_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.internal_static_com_zhaoyan_juyou_PBCancelReceiveFile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelReceiveFile.class, com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelReceiveFile.Builder.class);
    }

    public static com.google.protobuf.Parser<PBCancelReceiveFile> PARSER =
        new com.google.protobuf.AbstractParser<PBCancelReceiveFile>() {
      public PBCancelReceiveFile parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBCancelReceiveFile(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PBCancelReceiveFile> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 sendUserId = 1;
    public static final int SENDUSERID_FIELD_NUMBER = 1;
    private int sendUserId_;
    /**
     * <code>required int32 sendUserId = 1;</code>
     */
    public boolean hasSendUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 sendUserId = 1;</code>
     */
    public int getSendUserId() {
      return sendUserId_;
    }

    private void initFields() {
      sendUserId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSendUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, sendUserId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sendUserId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelReceiveFile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelReceiveFile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelReceiveFile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelReceiveFile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelReceiveFile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelReceiveFile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelReceiveFile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelReceiveFile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelReceiveFile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelReceiveFile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelReceiveFile prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zhaoyan.juyou.PBCancelReceiveFile}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelReceiveFileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.internal_static_com_zhaoyan_juyou_PBCancelReceiveFile_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.internal_static_com_zhaoyan_juyou_PBCancelReceiveFile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelReceiveFile.class, com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelReceiveFile.Builder.class);
      }

      // Construct using com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelReceiveFile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sendUserId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.internal_static_com_zhaoyan_juyou_PBCancelReceiveFile_descriptor;
      }

      public com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelReceiveFile getDefaultInstanceForType() {
        return com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelReceiveFile.getDefaultInstance();
      }

      public com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelReceiveFile build() {
        com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelReceiveFile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelReceiveFile buildPartial() {
        com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelReceiveFile result = new com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelReceiveFile(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sendUserId_ = sendUserId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelReceiveFile) {
          return mergeFrom((com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelReceiveFile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelReceiveFile other) {
        if (other == com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelReceiveFile.getDefaultInstance()) return this;
        if (other.hasSendUserId()) {
          setSendUserId(other.getSendUserId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSendUserId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelReceiveFile parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zhaoyan.communication.protocol.pb.PBFileTransportProtos.PBCancelReceiveFile) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 sendUserId = 1;
      private int sendUserId_ ;
      /**
       * <code>required int32 sendUserId = 1;</code>
       */
      public boolean hasSendUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 sendUserId = 1;</code>
       */
      public int getSendUserId() {
        return sendUserId_;
      }
      /**
       * <code>required int32 sendUserId = 1;</code>
       */
      public Builder setSendUserId(int value) {
        bitField0_ |= 0x00000001;
        sendUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 sendUserId = 1;</code>
       */
      public Builder clearSendUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sendUserId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.zhaoyan.juyou.PBCancelReceiveFile)
    }

    static {
      defaultInstance = new PBCancelReceiveFile(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.zhaoyan.juyou.PBCancelReceiveFile)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zhaoyan_juyou_PBSendFile_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zhaoyan_juyou_PBSendFile_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zhaoyan_juyou_PBFileInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zhaoyan_juyou_PBFileInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zhaoyan_juyou_PBCancelSendFile_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zhaoyan_juyou_PBCancelSendFile_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zhaoyan_juyou_PBCancelReceiveFile_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zhaoyan_juyou_PBCancelReceiveFile_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024file_transport.proto\022\021com.zhaoyan.juyo" +
      "u\"\242\001\n\nPBSendFile\022\022\n\nsendUserId\030\001 \002(\005\022\025\n\r" +
      "recieveUserId\030\002 \002(\005\022\r\n\005appId\030\003 \002(\005\022\025\n\rse" +
      "rverAddress\030\004 \001(\014\022\022\n\nserverPort\030\005 \001(\005\022/\n" +
      "\010fileInfo\030\006 \001(\0132\035.com.zhaoyan.juyou.PBFi" +
      "leInfo\"T\n\nPBFileInfo\022\020\n\010filePath\030\001 \002(\t\022\020" +
      "\n\010fileName\030\002 \002(\t\022\020\n\010fileSize\030\003 \002(\003\022\020\n\010fi" +
      "leIcon\030\004 \001(\014\")\n\020PBCancelSendFile\022\025\n\rrece" +
      "iveUserId\030\001 \002(\005\")\n\023PBCancelReceiveFile\022\022" +
      "\n\nsendUserId\030\001 \002(\005B>\n%com.zhaoyan.commun",
      "ication.protocol.pbB\025PBFileTransportProt" +
      "os"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_zhaoyan_juyou_PBSendFile_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_zhaoyan_juyou_PBSendFile_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_zhaoyan_juyou_PBSendFile_descriptor,
              new java.lang.String[] { "SendUserId", "RecieveUserId", "AppId", "ServerAddress", "ServerPort", "FileInfo", });
          internal_static_com_zhaoyan_juyou_PBFileInfo_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_zhaoyan_juyou_PBFileInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_zhaoyan_juyou_PBFileInfo_descriptor,
              new java.lang.String[] { "FilePath", "FileName", "FileSize", "FileIcon", });
          internal_static_com_zhaoyan_juyou_PBCancelSendFile_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_zhaoyan_juyou_PBCancelSendFile_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_zhaoyan_juyou_PBCancelSendFile_descriptor,
              new java.lang.String[] { "ReceiveUserId", });
          internal_static_com_zhaoyan_juyou_PBCancelReceiveFile_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_zhaoyan_juyou_PBCancelReceiveFile_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_zhaoyan_juyou_PBCancelReceiveFile_descriptor,
              new java.lang.String[] { "SendUserId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
