// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package com.zhaoyan.communication.protocol.pb;

public final class PBLoginProtos {
  private PBLoginProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.zhaoyan.juyou.PBLoginResult}
   */
  public enum PBLoginResult
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SUCCESS = 1;</code>
     */
    SUCCESS(0, 1),
    /**
     * <code>FAIL = 2;</code>
     */
    FAIL(1, 2),
    ;

    /**
     * <code>SUCCESS = 1;</code>
     */
    public static final int SUCCESS_VALUE = 1;
    /**
     * <code>FAIL = 2;</code>
     */
    public static final int FAIL_VALUE = 2;


    public final int getNumber() { return value; }

    public static PBLoginResult valueOf(int value) {
      switch (value) {
        case 1: return SUCCESS;
        case 2: return FAIL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PBLoginResult>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<PBLoginResult>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PBLoginResult>() {
            public PBLoginResult findValueByNumber(int number) {
              return PBLoginResult.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.zhaoyan.communication.protocol.pb.PBLoginProtos.getDescriptor().getEnumTypes().get(0);
    }

    private static final PBLoginResult[] VALUES = values();

    public static PBLoginResult valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private PBLoginResult(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.zhaoyan.juyou.PBLoginResult)
  }

  /**
   * Protobuf enum {@code com.zhaoyan.juyou.PBLoginFailReason}
   */
  public enum PBLoginFailReason
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKOWN = 1;</code>
     */
    UNKOWN(0, 1),
    ;

    /**
     * <code>UNKOWN = 1;</code>
     */
    public static final int UNKOWN_VALUE = 1;


    public final int getNumber() { return value; }

    public static PBLoginFailReason valueOf(int value) {
      switch (value) {
        case 1: return UNKOWN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PBLoginFailReason>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<PBLoginFailReason>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PBLoginFailReason>() {
            public PBLoginFailReason findValueByNumber(int number) {
              return PBLoginFailReason.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.zhaoyan.communication.protocol.pb.PBLoginProtos.getDescriptor().getEnumTypes().get(1);
    }

    private static final PBLoginFailReason[] VALUES = values();

    public static PBLoginFailReason valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private PBLoginFailReason(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.zhaoyan.juyou.PBLoginFailReason)
  }

  public interface PBLoginRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.zhaoyan.juyou.PBUserInfo userInfo = 1;
    /**
     * <code>required .com.zhaoyan.juyou.PBUserInfo userInfo = 1;</code>
     */
    boolean hasUserInfo();
    /**
     * <code>required .com.zhaoyan.juyou.PBUserInfo userInfo = 1;</code>
     */
    com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo getUserInfo();
    /**
     * <code>required .com.zhaoyan.juyou.PBUserInfo userInfo = 1;</code>
     */
    com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfoOrBuilder getUserInfoOrBuilder();
  }
  /**
   * Protobuf type {@code com.zhaoyan.juyou.PBLoginRequest}
   */
  public static final class PBLoginRequest extends
      com.google.protobuf.GeneratedMessage
      implements PBLoginRequestOrBuilder {
    // Use PBLoginRequest.newBuilder() to construct.
    private PBLoginRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PBLoginRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PBLoginRequest defaultInstance;
    public static PBLoginRequest getDefaultInstance() {
      return defaultInstance;
    }

    public PBLoginRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PBLoginRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = userInfo_.toBuilder();
              }
              userInfo_ = input.readMessage(com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(userInfo_);
                userInfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhaoyan.communication.protocol.pb.PBLoginProtos.internal_static_com_zhaoyan_juyou_PBLoginRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhaoyan.communication.protocol.pb.PBLoginProtos.internal_static_com_zhaoyan_juyou_PBLoginRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest.class, com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<PBLoginRequest> PARSER =
        new com.google.protobuf.AbstractParser<PBLoginRequest>() {
      public PBLoginRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBLoginRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PBLoginRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .com.zhaoyan.juyou.PBUserInfo userInfo = 1;
    public static final int USERINFO_FIELD_NUMBER = 1;
    private com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo userInfo_;
    /**
     * <code>required .com.zhaoyan.juyou.PBUserInfo userInfo = 1;</code>
     */
    public boolean hasUserInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.zhaoyan.juyou.PBUserInfo userInfo = 1;</code>
     */
    public com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo getUserInfo() {
      return userInfo_;
    }
    /**
     * <code>required .com.zhaoyan.juyou.PBUserInfo userInfo = 1;</code>
     */
    public com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfoOrBuilder getUserInfoOrBuilder() {
      return userInfo_;
    }

    private void initFields() {
      userInfo_ = com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserInfo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, userInfo_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, userInfo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zhaoyan.juyou.PBLoginRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zhaoyan.communication.protocol.pb.PBLoginProtos.internal_static_com_zhaoyan_juyou_PBLoginRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zhaoyan.communication.protocol.pb.PBLoginProtos.internal_static_com_zhaoyan_juyou_PBLoginRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest.class, com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest.Builder.class);
      }

      // Construct using com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUserInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (userInfoBuilder_ == null) {
          userInfo_ = com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo.getDefaultInstance();
        } else {
          userInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zhaoyan.communication.protocol.pb.PBLoginProtos.internal_static_com_zhaoyan_juyou_PBLoginRequest_descriptor;
      }

      public com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest getDefaultInstanceForType() {
        return com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest.getDefaultInstance();
      }

      public com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest build() {
        com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest buildPartial() {
        com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest result = new com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (userInfoBuilder_ == null) {
          result.userInfo_ = userInfo_;
        } else {
          result.userInfo_ = userInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest) {
          return mergeFrom((com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest other) {
        if (other == com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest.getDefaultInstance()) return this;
        if (other.hasUserInfo()) {
          mergeUserInfo(other.getUserInfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserInfo()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.zhaoyan.juyou.PBUserInfo userInfo = 1;
      private com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo userInfo_ = com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo, com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo.Builder, com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfoOrBuilder> userInfoBuilder_;
      /**
       * <code>required .com.zhaoyan.juyou.PBUserInfo userInfo = 1;</code>
       */
      public boolean hasUserInfo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.zhaoyan.juyou.PBUserInfo userInfo = 1;</code>
       */
      public com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo getUserInfo() {
        if (userInfoBuilder_ == null) {
          return userInfo_;
        } else {
          return userInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.zhaoyan.juyou.PBUserInfo userInfo = 1;</code>
       */
      public Builder setUserInfo(com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo value) {
        if (userInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          userInfo_ = value;
          onChanged();
        } else {
          userInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.zhaoyan.juyou.PBUserInfo userInfo = 1;</code>
       */
      public Builder setUserInfo(
          com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo.Builder builderForValue) {
        if (userInfoBuilder_ == null) {
          userInfo_ = builderForValue.build();
          onChanged();
        } else {
          userInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.zhaoyan.juyou.PBUserInfo userInfo = 1;</code>
       */
      public Builder mergeUserInfo(com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo value) {
        if (userInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              userInfo_ != com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo.getDefaultInstance()) {
            userInfo_ =
              com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo.newBuilder(userInfo_).mergeFrom(value).buildPartial();
          } else {
            userInfo_ = value;
          }
          onChanged();
        } else {
          userInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.zhaoyan.juyou.PBUserInfo userInfo = 1;</code>
       */
      public Builder clearUserInfo() {
        if (userInfoBuilder_ == null) {
          userInfo_ = com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo.getDefaultInstance();
          onChanged();
        } else {
          userInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .com.zhaoyan.juyou.PBUserInfo userInfo = 1;</code>
       */
      public com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo.Builder getUserInfoBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getUserInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.zhaoyan.juyou.PBUserInfo userInfo = 1;</code>
       */
      public com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfoOrBuilder getUserInfoOrBuilder() {
        if (userInfoBuilder_ != null) {
          return userInfoBuilder_.getMessageOrBuilder();
        } else {
          return userInfo_;
        }
      }
      /**
       * <code>required .com.zhaoyan.juyou.PBUserInfo userInfo = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo, com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo.Builder, com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfoOrBuilder> 
          getUserInfoFieldBuilder() {
        if (userInfoBuilder_ == null) {
          userInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo, com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo.Builder, com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfoOrBuilder>(
                  userInfo_,
                  getParentForChildren(),
                  isClean());
          userInfo_ = null;
        }
        return userInfoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.zhaoyan.juyou.PBLoginRequest)
    }

    static {
      defaultInstance = new PBLoginRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.zhaoyan.juyou.PBLoginRequest)
  }

  public interface PBLoginRespondOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.zhaoyan.juyou.PBLoginResult result = 1;
    /**
     * <code>required .com.zhaoyan.juyou.PBLoginResult result = 1;</code>
     */
    boolean hasResult();
    /**
     * <code>required .com.zhaoyan.juyou.PBLoginResult result = 1;</code>
     */
    com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginResult getResult();

    // optional int32 userId = 2;
    /**
     * <code>optional int32 userId = 2;</code>
     */
    boolean hasUserId();
    /**
     * <code>optional int32 userId = 2;</code>
     */
    int getUserId();

    // optional .com.zhaoyan.juyou.PBLoginFailReason failReason = 3;
    /**
     * <code>optional .com.zhaoyan.juyou.PBLoginFailReason failReason = 3;</code>
     */
    boolean hasFailReason();
    /**
     * <code>optional .com.zhaoyan.juyou.PBLoginFailReason failReason = 3;</code>
     */
    com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginFailReason getFailReason();
  }
  /**
   * Protobuf type {@code com.zhaoyan.juyou.PBLoginRespond}
   */
  public static final class PBLoginRespond extends
      com.google.protobuf.GeneratedMessage
      implements PBLoginRespondOrBuilder {
    // Use PBLoginRespond.newBuilder() to construct.
    private PBLoginRespond(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PBLoginRespond(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PBLoginRespond defaultInstance;
    public static PBLoginRespond getDefaultInstance() {
      return defaultInstance;
    }

    public PBLoginRespond getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PBLoginRespond(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginResult value = com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginResult.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                result_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              userId_ = input.readInt32();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginFailReason value = com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginFailReason.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                failReason_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhaoyan.communication.protocol.pb.PBLoginProtos.internal_static_com_zhaoyan_juyou_PBLoginRespond_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhaoyan.communication.protocol.pb.PBLoginProtos.internal_static_com_zhaoyan_juyou_PBLoginRespond_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond.class, com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond.Builder.class);
    }

    public static com.google.protobuf.Parser<PBLoginRespond> PARSER =
        new com.google.protobuf.AbstractParser<PBLoginRespond>() {
      public PBLoginRespond parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBLoginRespond(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PBLoginRespond> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .com.zhaoyan.juyou.PBLoginResult result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginResult result_;
    /**
     * <code>required .com.zhaoyan.juyou.PBLoginResult result = 1;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.zhaoyan.juyou.PBLoginResult result = 1;</code>
     */
    public com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginResult getResult() {
      return result_;
    }

    // optional int32 userId = 2;
    public static final int USERID_FIELD_NUMBER = 2;
    private int userId_;
    /**
     * <code>optional int32 userId = 2;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 userId = 2;</code>
     */
    public int getUserId() {
      return userId_;
    }

    // optional .com.zhaoyan.juyou.PBLoginFailReason failReason = 3;
    public static final int FAILREASON_FIELD_NUMBER = 3;
    private com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginFailReason failReason_;
    /**
     * <code>optional .com.zhaoyan.juyou.PBLoginFailReason failReason = 3;</code>
     */
    public boolean hasFailReason() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .com.zhaoyan.juyou.PBLoginFailReason failReason = 3;</code>
     */
    public com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginFailReason getFailReason() {
      return failReason_;
    }

    private void initFields() {
      result_ = com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginResult.SUCCESS;
      userId_ = 0;
      failReason_ = com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginFailReason.UNKOWN;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, result_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, userId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, failReason_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, result_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, userId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, failReason_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zhaoyan.juyou.PBLoginRespond}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespondOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zhaoyan.communication.protocol.pb.PBLoginProtos.internal_static_com_zhaoyan_juyou_PBLoginRespond_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zhaoyan.communication.protocol.pb.PBLoginProtos.internal_static_com_zhaoyan_juyou_PBLoginRespond_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond.class, com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond.Builder.class);
      }

      // Construct using com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginResult.SUCCESS;
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        failReason_ = com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginFailReason.UNKOWN;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zhaoyan.communication.protocol.pb.PBLoginProtos.internal_static_com_zhaoyan_juyou_PBLoginRespond_descriptor;
      }

      public com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond getDefaultInstanceForType() {
        return com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond.getDefaultInstance();
      }

      public com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond build() {
        com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond buildPartial() {
        com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond result = new com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.failReason_ = failReason_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond) {
          return mergeFrom((com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond other) {
        if (other == com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasFailReason()) {
          setFailReason(other.getFailReason());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResult()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.zhaoyan.juyou.PBLoginResult result = 1;
      private com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginResult result_ = com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginResult.SUCCESS;
      /**
       * <code>required .com.zhaoyan.juyou.PBLoginResult result = 1;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.zhaoyan.juyou.PBLoginResult result = 1;</code>
       */
      public com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginResult getResult() {
        return result_;
      }
      /**
       * <code>required .com.zhaoyan.juyou.PBLoginResult result = 1;</code>
       */
      public Builder setResult(com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginResult value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.zhaoyan.juyou.PBLoginResult result = 1;</code>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginResult.SUCCESS;
        onChanged();
        return this;
      }

      // optional int32 userId = 2;
      private int userId_ ;
      /**
       * <code>optional int32 userId = 2;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 userId = 2;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>optional int32 userId = 2;</code>
       */
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000002;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 userId = 2;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userId_ = 0;
        onChanged();
        return this;
      }

      // optional .com.zhaoyan.juyou.PBLoginFailReason failReason = 3;
      private com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginFailReason failReason_ = com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginFailReason.UNKOWN;
      /**
       * <code>optional .com.zhaoyan.juyou.PBLoginFailReason failReason = 3;</code>
       */
      public boolean hasFailReason() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .com.zhaoyan.juyou.PBLoginFailReason failReason = 3;</code>
       */
      public com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginFailReason getFailReason() {
        return failReason_;
      }
      /**
       * <code>optional .com.zhaoyan.juyou.PBLoginFailReason failReason = 3;</code>
       */
      public Builder setFailReason(com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginFailReason value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        failReason_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.zhaoyan.juyou.PBLoginFailReason failReason = 3;</code>
       */
      public Builder clearFailReason() {
        bitField0_ = (bitField0_ & ~0x00000004);
        failReason_ = com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginFailReason.UNKOWN;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.zhaoyan.juyou.PBLoginRespond)
    }

    static {
      defaultInstance = new PBLoginRespond(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.zhaoyan.juyou.PBLoginRespond)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zhaoyan_juyou_PBLoginRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zhaoyan_juyou_PBLoginRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zhaoyan_juyou_PBLoginRespond_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zhaoyan_juyou_PBLoginRespond_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013login.proto\022\021com.zhaoyan.juyou\032\017user_i" +
      "nfo.proto\"A\n\016PBLoginRequest\022/\n\010userInfo\030" +
      "\001 \002(\0132\035.com.zhaoyan.juyou.PBUserInfo\"\214\001\n" +
      "\016PBLoginRespond\0220\n\006result\030\001 \002(\0162 .com.zh" +
      "aoyan.juyou.PBLoginResult\022\016\n\006userId\030\002 \001(" +
      "\005\0228\n\nfailReason\030\003 \001(\0162$.com.zhaoyan.juyo" +
      "u.PBLoginFailReason*&\n\rPBLoginResult\022\013\n\007" +
      "SUCCESS\020\001\022\010\n\004FAIL\020\002*\037\n\021PBLoginFailReason" +
      "\022\n\n\006UNKOWN\020\001B6\n%com.zhaoyan.communicatio" +
      "n.protocol.pbB\rPBLoginProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_zhaoyan_juyou_PBLoginRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_zhaoyan_juyou_PBLoginRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_zhaoyan_juyou_PBLoginRequest_descriptor,
              new java.lang.String[] { "UserInfo", });
          internal_static_com_zhaoyan_juyou_PBLoginRespond_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_zhaoyan_juyou_PBLoginRespond_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_zhaoyan_juyou_PBLoginRespond_descriptor,
              new java.lang.String[] { "Result", "UserId", "FailReason", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
