// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_send.proto

package com.zhaoyan.communication.protocol.pb;

public final class PBSendMessageProtos {
  private PBSendMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PBSendMessageToSingleOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 sendUserId = 1;
    /**
     * <code>required int32 sendUserId = 1;</code>
     */
    boolean hasSendUserId();
    /**
     * <code>required int32 sendUserId = 1;</code>
     */
    int getSendUserId();

    // required int32 receiveUserId = 2;
    /**
     * <code>required int32 receiveUserId = 2;</code>
     */
    boolean hasReceiveUserId();
    /**
     * <code>required int32 receiveUserId = 2;</code>
     */
    int getReceiveUserId();

    // required int32 appId = 3;
    /**
     * <code>required int32 appId = 3;</code>
     */
    boolean hasAppId();
    /**
     * <code>required int32 appId = 3;</code>
     */
    int getAppId();

    // required bytes data = 4;
    /**
     * <code>required bytes data = 4;</code>
     */
    boolean hasData();
    /**
     * <code>required bytes data = 4;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code com.zhaoyan.juyou.PBSendMessageToSingle}
   */
  public static final class PBSendMessageToSingle extends
      com.google.protobuf.GeneratedMessage
      implements PBSendMessageToSingleOrBuilder {
    // Use PBSendMessageToSingle.newBuilder() to construct.
    private PBSendMessageToSingle(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PBSendMessageToSingle(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PBSendMessageToSingle defaultInstance;
    public static PBSendMessageToSingle getDefaultInstance() {
      return defaultInstance;
    }

    public PBSendMessageToSingle getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PBSendMessageToSingle(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              sendUserId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              receiveUserId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              appId_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.internal_static_com_zhaoyan_juyou_PBSendMessageToSingle_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.internal_static_com_zhaoyan_juyou_PBSendMessageToSingle_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToSingle.class, com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToSingle.Builder.class);
    }

    public static com.google.protobuf.Parser<PBSendMessageToSingle> PARSER =
        new com.google.protobuf.AbstractParser<PBSendMessageToSingle>() {
      public PBSendMessageToSingle parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBSendMessageToSingle(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PBSendMessageToSingle> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 sendUserId = 1;
    public static final int SENDUSERID_FIELD_NUMBER = 1;
    private int sendUserId_;
    /**
     * <code>required int32 sendUserId = 1;</code>
     */
    public boolean hasSendUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 sendUserId = 1;</code>
     */
    public int getSendUserId() {
      return sendUserId_;
    }

    // required int32 receiveUserId = 2;
    public static final int RECEIVEUSERID_FIELD_NUMBER = 2;
    private int receiveUserId_;
    /**
     * <code>required int32 receiveUserId = 2;</code>
     */
    public boolean hasReceiveUserId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 receiveUserId = 2;</code>
     */
    public int getReceiveUserId() {
      return receiveUserId_;
    }

    // required int32 appId = 3;
    public static final int APPID_FIELD_NUMBER = 3;
    private int appId_;
    /**
     * <code>required int32 appId = 3;</code>
     */
    public boolean hasAppId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 appId = 3;</code>
     */
    public int getAppId() {
      return appId_;
    }

    // required bytes data = 4;
    public static final int DATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>required bytes data = 4;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes data = 4;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private void initFields() {
      sendUserId_ = 0;
      receiveUserId_ = 0;
      appId_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSendUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReceiveUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAppId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, sendUserId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, receiveUserId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, appId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, data_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sendUserId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, receiveUserId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, appId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToSingle parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToSingle parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToSingle parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToSingle parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToSingle parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToSingle parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToSingle parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToSingle parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToSingle parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToSingle parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToSingle prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zhaoyan.juyou.PBSendMessageToSingle}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToSingleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.internal_static_com_zhaoyan_juyou_PBSendMessageToSingle_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.internal_static_com_zhaoyan_juyou_PBSendMessageToSingle_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToSingle.class, com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToSingle.Builder.class);
      }

      // Construct using com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToSingle.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sendUserId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        receiveUserId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        appId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.internal_static_com_zhaoyan_juyou_PBSendMessageToSingle_descriptor;
      }

      public com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToSingle getDefaultInstanceForType() {
        return com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToSingle.getDefaultInstance();
      }

      public com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToSingle build() {
        com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToSingle result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToSingle buildPartial() {
        com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToSingle result = new com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToSingle(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sendUserId_ = sendUserId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.receiveUserId_ = receiveUserId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.appId_ = appId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToSingle) {
          return mergeFrom((com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToSingle)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToSingle other) {
        if (other == com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToSingle.getDefaultInstance()) return this;
        if (other.hasSendUserId()) {
          setSendUserId(other.getSendUserId());
        }
        if (other.hasReceiveUserId()) {
          setReceiveUserId(other.getReceiveUserId());
        }
        if (other.hasAppId()) {
          setAppId(other.getAppId());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSendUserId()) {
          
          return false;
        }
        if (!hasReceiveUserId()) {
          
          return false;
        }
        if (!hasAppId()) {
          
          return false;
        }
        if (!hasData()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToSingle parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToSingle) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 sendUserId = 1;
      private int sendUserId_ ;
      /**
       * <code>required int32 sendUserId = 1;</code>
       */
      public boolean hasSendUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 sendUserId = 1;</code>
       */
      public int getSendUserId() {
        return sendUserId_;
      }
      /**
       * <code>required int32 sendUserId = 1;</code>
       */
      public Builder setSendUserId(int value) {
        bitField0_ |= 0x00000001;
        sendUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 sendUserId = 1;</code>
       */
      public Builder clearSendUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sendUserId_ = 0;
        onChanged();
        return this;
      }

      // required int32 receiveUserId = 2;
      private int receiveUserId_ ;
      /**
       * <code>required int32 receiveUserId = 2;</code>
       */
      public boolean hasReceiveUserId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 receiveUserId = 2;</code>
       */
      public int getReceiveUserId() {
        return receiveUserId_;
      }
      /**
       * <code>required int32 receiveUserId = 2;</code>
       */
      public Builder setReceiveUserId(int value) {
        bitField0_ |= 0x00000002;
        receiveUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 receiveUserId = 2;</code>
       */
      public Builder clearReceiveUserId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        receiveUserId_ = 0;
        onChanged();
        return this;
      }

      // required int32 appId = 3;
      private int appId_ ;
      /**
       * <code>required int32 appId = 3;</code>
       */
      public boolean hasAppId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 appId = 3;</code>
       */
      public int getAppId() {
        return appId_;
      }
      /**
       * <code>required int32 appId = 3;</code>
       */
      public Builder setAppId(int value) {
        bitField0_ |= 0x00000004;
        appId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 appId = 3;</code>
       */
      public Builder clearAppId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        appId_ = 0;
        onChanged();
        return this;
      }

      // required bytes data = 4;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes data = 4;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes data = 4;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>required bytes data = 4;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes data = 4;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.zhaoyan.juyou.PBSendMessageToSingle)
    }

    static {
      defaultInstance = new PBSendMessageToSingle(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.zhaoyan.juyou.PBSendMessageToSingle)
  }

  public interface PBSendMessageToAllOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 sendUserId = 1;
    /**
     * <code>required int32 sendUserId = 1;</code>
     */
    boolean hasSendUserId();
    /**
     * <code>required int32 sendUserId = 1;</code>
     */
    int getSendUserId();

    // required int32 appId = 2;
    /**
     * <code>required int32 appId = 2;</code>
     */
    boolean hasAppId();
    /**
     * <code>required int32 appId = 2;</code>
     */
    int getAppId();

    // required bytes data = 3;
    /**
     * <code>required bytes data = 3;</code>
     */
    boolean hasData();
    /**
     * <code>required bytes data = 3;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code com.zhaoyan.juyou.PBSendMessageToAll}
   */
  public static final class PBSendMessageToAll extends
      com.google.protobuf.GeneratedMessage
      implements PBSendMessageToAllOrBuilder {
    // Use PBSendMessageToAll.newBuilder() to construct.
    private PBSendMessageToAll(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PBSendMessageToAll(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PBSendMessageToAll defaultInstance;
    public static PBSendMessageToAll getDefaultInstance() {
      return defaultInstance;
    }

    public PBSendMessageToAll getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PBSendMessageToAll(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              sendUserId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              appId_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.internal_static_com_zhaoyan_juyou_PBSendMessageToAll_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.internal_static_com_zhaoyan_juyou_PBSendMessageToAll_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToAll.class, com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToAll.Builder.class);
    }

    public static com.google.protobuf.Parser<PBSendMessageToAll> PARSER =
        new com.google.protobuf.AbstractParser<PBSendMessageToAll>() {
      public PBSendMessageToAll parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBSendMessageToAll(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PBSendMessageToAll> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 sendUserId = 1;
    public static final int SENDUSERID_FIELD_NUMBER = 1;
    private int sendUserId_;
    /**
     * <code>required int32 sendUserId = 1;</code>
     */
    public boolean hasSendUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 sendUserId = 1;</code>
     */
    public int getSendUserId() {
      return sendUserId_;
    }

    // required int32 appId = 2;
    public static final int APPID_FIELD_NUMBER = 2;
    private int appId_;
    /**
     * <code>required int32 appId = 2;</code>
     */
    public boolean hasAppId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 appId = 2;</code>
     */
    public int getAppId() {
      return appId_;
    }

    // required bytes data = 3;
    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>required bytes data = 3;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes data = 3;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private void initFields() {
      sendUserId_ = 0;
      appId_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSendUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAppId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, sendUserId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, appId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, data_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sendUserId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, appId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToAll parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToAll parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToAll parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToAll parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToAll parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToAll parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToAll parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToAll parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToAll parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToAll parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToAll prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zhaoyan.juyou.PBSendMessageToAll}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToAllOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.internal_static_com_zhaoyan_juyou_PBSendMessageToAll_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.internal_static_com_zhaoyan_juyou_PBSendMessageToAll_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToAll.class, com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToAll.Builder.class);
      }

      // Construct using com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToAll.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sendUserId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        appId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.internal_static_com_zhaoyan_juyou_PBSendMessageToAll_descriptor;
      }

      public com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToAll getDefaultInstanceForType() {
        return com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToAll.getDefaultInstance();
      }

      public com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToAll build() {
        com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToAll result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToAll buildPartial() {
        com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToAll result = new com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToAll(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sendUserId_ = sendUserId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.appId_ = appId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToAll) {
          return mergeFrom((com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToAll)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToAll other) {
        if (other == com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToAll.getDefaultInstance()) return this;
        if (other.hasSendUserId()) {
          setSendUserId(other.getSendUserId());
        }
        if (other.hasAppId()) {
          setAppId(other.getAppId());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSendUserId()) {
          
          return false;
        }
        if (!hasAppId()) {
          
          return false;
        }
        if (!hasData()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToAll parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zhaoyan.communication.protocol.pb.PBSendMessageProtos.PBSendMessageToAll) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 sendUserId = 1;
      private int sendUserId_ ;
      /**
       * <code>required int32 sendUserId = 1;</code>
       */
      public boolean hasSendUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 sendUserId = 1;</code>
       */
      public int getSendUserId() {
        return sendUserId_;
      }
      /**
       * <code>required int32 sendUserId = 1;</code>
       */
      public Builder setSendUserId(int value) {
        bitField0_ |= 0x00000001;
        sendUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 sendUserId = 1;</code>
       */
      public Builder clearSendUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sendUserId_ = 0;
        onChanged();
        return this;
      }

      // required int32 appId = 2;
      private int appId_ ;
      /**
       * <code>required int32 appId = 2;</code>
       */
      public boolean hasAppId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 appId = 2;</code>
       */
      public int getAppId() {
        return appId_;
      }
      /**
       * <code>required int32 appId = 2;</code>
       */
      public Builder setAppId(int value) {
        bitField0_ |= 0x00000002;
        appId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 appId = 2;</code>
       */
      public Builder clearAppId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        appId_ = 0;
        onChanged();
        return this;
      }

      // required bytes data = 3;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes data = 3;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes data = 3;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>required bytes data = 3;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes data = 3;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.zhaoyan.juyou.PBSendMessageToAll)
    }

    static {
      defaultInstance = new PBSendMessageToAll(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.zhaoyan.juyou.PBSendMessageToAll)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zhaoyan_juyou_PBSendMessageToSingle_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zhaoyan_juyou_PBSendMessageToSingle_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zhaoyan_juyou_PBSendMessageToAll_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zhaoyan_juyou_PBSendMessageToAll_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022message_send.proto\022\021com.zhaoyan.juyou\"" +
      "_\n\025PBSendMessageToSingle\022\022\n\nsendUserId\030\001" +
      " \002(\005\022\025\n\rreceiveUserId\030\002 \002(\005\022\r\n\005appId\030\003 \002" +
      "(\005\022\014\n\004data\030\004 \002(\014\"E\n\022PBSendMessageToAll\022\022" +
      "\n\nsendUserId\030\001 \002(\005\022\r\n\005appId\030\002 \002(\005\022\014\n\004dat" +
      "a\030\003 \002(\014B<\n%com.zhaoyan.communication.pro" +
      "tocol.pbB\023PBSendMessageProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_zhaoyan_juyou_PBSendMessageToSingle_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_zhaoyan_juyou_PBSendMessageToSingle_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_zhaoyan_juyou_PBSendMessageToSingle_descriptor,
              new java.lang.String[] { "SendUserId", "ReceiveUserId", "AppId", "Data", });
          internal_static_com_zhaoyan_juyou_PBSendMessageToAll_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_zhaoyan_juyou_PBSendMessageToAll_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_zhaoyan_juyou_PBSendMessageToAll_descriptor,
              new java.lang.String[] { "SendUserId", "AppId", "Data", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
