// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_info.proto

package com.zhaoyan.communication.protocol.pb;

public final class PBUserInfoProtos {
  private PBUserInfoProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PBUserInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 userId = 1;
    /**
     * <code>optional int32 userId = 1;</code>
     */
    boolean hasUserId();
    /**
     * <code>optional int32 userId = 1;</code>
     */
    int getUserId();

    // optional string userName = 2;
    /**
     * <code>optional string userName = 2;</code>
     */
    boolean hasUserName();
    /**
     * <code>optional string userName = 2;</code>
     */
    java.lang.String getUserName();
    /**
     * <code>optional string userName = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    // optional int32 headImageId = 3;
    /**
     * <code>optional int32 headImageId = 3;</code>
     */
    boolean hasHeadImageId();
    /**
     * <code>optional int32 headImageId = 3;</code>
     */
    int getHeadImageId();

    // optional bytes headImageData = 4;
    /**
     * <code>optional bytes headImageData = 4;</code>
     */
    boolean hasHeadImageData();
    /**
     * <code>optional bytes headImageData = 4;</code>
     */
    com.google.protobuf.ByteString getHeadImageData();

    // optional string ipAddress = 5;
    /**
     * <code>optional string ipAddress = 5;</code>
     */
    boolean hasIpAddress();
    /**
     * <code>optional string ipAddress = 5;</code>
     */
    java.lang.String getIpAddress();
    /**
     * <code>optional string ipAddress = 5;</code>
     */
    com.google.protobuf.ByteString
        getIpAddressBytes();

    // optional int32 type = 6;
    /**
     * <code>optional int32 type = 6;</code>
     */
    boolean hasType();
    /**
     * <code>optional int32 type = 6;</code>
     */
    int getType();

    // optional string ssid = 7;
    /**
     * <code>optional string ssid = 7;</code>
     */
    boolean hasSsid();
    /**
     * <code>optional string ssid = 7;</code>
     */
    java.lang.String getSsid();
    /**
     * <code>optional string ssid = 7;</code>
     */
    com.google.protobuf.ByteString
        getSsidBytes();

    // optional int32 status = 8;
    /**
     * <code>optional int32 status = 8;</code>
     */
    boolean hasStatus();
    /**
     * <code>optional int32 status = 8;</code>
     */
    int getStatus();

    // optional int32 networkType = 9;
    /**
     * <code>optional int32 networkType = 9;</code>
     */
    boolean hasNetworkType();
    /**
     * <code>optional int32 networkType = 9;</code>
     */
    int getNetworkType();

    // optional string signature = 10;
    /**
     * <code>optional string signature = 10;</code>
     */
    boolean hasSignature();
    /**
     * <code>optional string signature = 10;</code>
     */
    java.lang.String getSignature();
    /**
     * <code>optional string signature = 10;</code>
     */
    com.google.protobuf.ByteString
        getSignatureBytes();
  }
  /**
   * Protobuf type {@code com.zhaoyan.juyou.PBUserInfo}
   */
  public static final class PBUserInfo extends
      com.google.protobuf.GeneratedMessage
      implements PBUserInfoOrBuilder {
    // Use PBUserInfo.newBuilder() to construct.
    private PBUserInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PBUserInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PBUserInfo defaultInstance;
    public static PBUserInfo getDefaultInstance() {
      return defaultInstance;
    }

    public PBUserInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PBUserInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              userName_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              headImageId_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              headImageData_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              ipAddress_ = input.readBytes();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              type_ = input.readInt32();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              ssid_ = input.readBytes();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              status_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              networkType_ = input.readInt32();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              signature_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.internal_static_com_zhaoyan_juyou_PBUserInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.internal_static_com_zhaoyan_juyou_PBUserInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo.class, com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<PBUserInfo> PARSER =
        new com.google.protobuf.AbstractParser<PBUserInfo>() {
      public PBUserInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBUserInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PBUserInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 userId = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <code>optional int32 userId = 1;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 userId = 1;</code>
     */
    public int getUserId() {
      return userId_;
    }

    // optional string userName = 2;
    public static final int USERNAME_FIELD_NUMBER = 2;
    private java.lang.Object userName_;
    /**
     * <code>optional string userName = 2;</code>
     */
    public boolean hasUserName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string userName = 2;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string userName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 headImageId = 3;
    public static final int HEADIMAGEID_FIELD_NUMBER = 3;
    private int headImageId_;
    /**
     * <code>optional int32 headImageId = 3;</code>
     */
    public boolean hasHeadImageId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 headImageId = 3;</code>
     */
    public int getHeadImageId() {
      return headImageId_;
    }

    // optional bytes headImageData = 4;
    public static final int HEADIMAGEDATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString headImageData_;
    /**
     * <code>optional bytes headImageData = 4;</code>
     */
    public boolean hasHeadImageData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes headImageData = 4;</code>
     */
    public com.google.protobuf.ByteString getHeadImageData() {
      return headImageData_;
    }

    // optional string ipAddress = 5;
    public static final int IPADDRESS_FIELD_NUMBER = 5;
    private java.lang.Object ipAddress_;
    /**
     * <code>optional string ipAddress = 5;</code>
     */
    public boolean hasIpAddress() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string ipAddress = 5;</code>
     */
    public java.lang.String getIpAddress() {
      java.lang.Object ref = ipAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ipAddress_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string ipAddress = 5;</code>
     */
    public com.google.protobuf.ByteString
        getIpAddressBytes() {
      java.lang.Object ref = ipAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ipAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 type = 6;
    public static final int TYPE_FIELD_NUMBER = 6;
    private int type_;
    /**
     * <code>optional int32 type = 6;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 type = 6;</code>
     */
    public int getType() {
      return type_;
    }

    // optional string ssid = 7;
    public static final int SSID_FIELD_NUMBER = 7;
    private java.lang.Object ssid_;
    /**
     * <code>optional string ssid = 7;</code>
     */
    public boolean hasSsid() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string ssid = 7;</code>
     */
    public java.lang.String getSsid() {
      java.lang.Object ref = ssid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ssid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string ssid = 7;</code>
     */
    public com.google.protobuf.ByteString
        getSsidBytes() {
      java.lang.Object ref = ssid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ssid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 status = 8;
    public static final int STATUS_FIELD_NUMBER = 8;
    private int status_;
    /**
     * <code>optional int32 status = 8;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 status = 8;</code>
     */
    public int getStatus() {
      return status_;
    }

    // optional int32 networkType = 9;
    public static final int NETWORKTYPE_FIELD_NUMBER = 9;
    private int networkType_;
    /**
     * <code>optional int32 networkType = 9;</code>
     */
    public boolean hasNetworkType() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int32 networkType = 9;</code>
     */
    public int getNetworkType() {
      return networkType_;
    }

    // optional string signature = 10;
    public static final int SIGNATURE_FIELD_NUMBER = 10;
    private java.lang.Object signature_;
    /**
     * <code>optional string signature = 10;</code>
     */
    public boolean hasSignature() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string signature = 10;</code>
     */
    public java.lang.String getSignature() {
      java.lang.Object ref = signature_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          signature_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string signature = 10;</code>
     */
    public com.google.protobuf.ByteString
        getSignatureBytes() {
      java.lang.Object ref = signature_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signature_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      userId_ = 0;
      userName_ = "";
      headImageId_ = 0;
      headImageData_ = com.google.protobuf.ByteString.EMPTY;
      ipAddress_ = "";
      type_ = 0;
      ssid_ = "";
      status_ = 0;
      networkType_ = 0;
      signature_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUserNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, headImageId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, headImageData_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getIpAddressBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, type_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getSsidBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, status_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, networkType_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getSignatureBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUserNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, headImageId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, headImageData_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getIpAddressBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, type_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getSsidBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, status_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, networkType_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getSignatureBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zhaoyan.juyou.PBUserInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.internal_static_com_zhaoyan_juyou_PBUserInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.internal_static_com_zhaoyan_juyou_PBUserInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo.class, com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo.Builder.class);
      }

      // Construct using com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        userName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        headImageId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        headImageData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        ipAddress_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        ssid_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        networkType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        signature_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.internal_static_com_zhaoyan_juyou_PBUserInfo_descriptor;
      }

      public com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo getDefaultInstanceForType() {
        return com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo.getDefaultInstance();
      }

      public com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo build() {
        com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo buildPartial() {
        com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo result = new com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userName_ = userName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.headImageId_ = headImageId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.headImageData_ = headImageData_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.ipAddress_ = ipAddress_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.ssid_ = ssid_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.networkType_ = networkType_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.signature_ = signature_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo) {
          return mergeFrom((com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo other) {
        if (other == com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasUserName()) {
          bitField0_ |= 0x00000002;
          userName_ = other.userName_;
          onChanged();
        }
        if (other.hasHeadImageId()) {
          setHeadImageId(other.getHeadImageId());
        }
        if (other.hasHeadImageData()) {
          setHeadImageData(other.getHeadImageData());
        }
        if (other.hasIpAddress()) {
          bitField0_ |= 0x00000010;
          ipAddress_ = other.ipAddress_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasSsid()) {
          bitField0_ |= 0x00000040;
          ssid_ = other.ssid_;
          onChanged();
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasNetworkType()) {
          setNetworkType(other.getNetworkType());
        }
        if (other.hasSignature()) {
          bitField0_ |= 0x00000200;
          signature_ = other.signature_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 userId = 1;
      private int userId_ ;
      /**
       * <code>optional int32 userId = 1;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 userId = 1;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>optional int32 userId = 1;</code>
       */
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 userId = 1;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        onChanged();
        return this;
      }

      // optional string userName = 2;
      private java.lang.Object userName_ = "";
      /**
       * <code>optional string userName = 2;</code>
       */
      public boolean hasUserName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string userName = 2;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userName = 2;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userName = 2;</code>
       */
      public Builder clearUserName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userName = 2;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userName_ = value;
        onChanged();
        return this;
      }

      // optional int32 headImageId = 3;
      private int headImageId_ ;
      /**
       * <code>optional int32 headImageId = 3;</code>
       */
      public boolean hasHeadImageId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 headImageId = 3;</code>
       */
      public int getHeadImageId() {
        return headImageId_;
      }
      /**
       * <code>optional int32 headImageId = 3;</code>
       */
      public Builder setHeadImageId(int value) {
        bitField0_ |= 0x00000004;
        headImageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 headImageId = 3;</code>
       */
      public Builder clearHeadImageId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        headImageId_ = 0;
        onChanged();
        return this;
      }

      // optional bytes headImageData = 4;
      private com.google.protobuf.ByteString headImageData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes headImageData = 4;</code>
       */
      public boolean hasHeadImageData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes headImageData = 4;</code>
       */
      public com.google.protobuf.ByteString getHeadImageData() {
        return headImageData_;
      }
      /**
       * <code>optional bytes headImageData = 4;</code>
       */
      public Builder setHeadImageData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        headImageData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes headImageData = 4;</code>
       */
      public Builder clearHeadImageData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        headImageData_ = getDefaultInstance().getHeadImageData();
        onChanged();
        return this;
      }

      // optional string ipAddress = 5;
      private java.lang.Object ipAddress_ = "";
      /**
       * <code>optional string ipAddress = 5;</code>
       */
      public boolean hasIpAddress() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string ipAddress = 5;</code>
       */
      public java.lang.String getIpAddress() {
        java.lang.Object ref = ipAddress_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          ipAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ipAddress = 5;</code>
       */
      public com.google.protobuf.ByteString
          getIpAddressBytes() {
        java.lang.Object ref = ipAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ipAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ipAddress = 5;</code>
       */
      public Builder setIpAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        ipAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ipAddress = 5;</code>
       */
      public Builder clearIpAddress() {
        bitField0_ = (bitField0_ & ~0x00000010);
        ipAddress_ = getDefaultInstance().getIpAddress();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ipAddress = 5;</code>
       */
      public Builder setIpAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        ipAddress_ = value;
        onChanged();
        return this;
      }

      // optional int32 type = 6;
      private int type_ ;
      /**
       * <code>optional int32 type = 6;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 type = 6;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>optional int32 type = 6;</code>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000020;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 type = 6;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        type_ = 0;
        onChanged();
        return this;
      }

      // optional string ssid = 7;
      private java.lang.Object ssid_ = "";
      /**
       * <code>optional string ssid = 7;</code>
       */
      public boolean hasSsid() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string ssid = 7;</code>
       */
      public java.lang.String getSsid() {
        java.lang.Object ref = ssid_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          ssid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ssid = 7;</code>
       */
      public com.google.protobuf.ByteString
          getSsidBytes() {
        java.lang.Object ref = ssid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ssid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ssid = 7;</code>
       */
      public Builder setSsid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        ssid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ssid = 7;</code>
       */
      public Builder clearSsid() {
        bitField0_ = (bitField0_ & ~0x00000040);
        ssid_ = getDefaultInstance().getSsid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ssid = 7;</code>
       */
      public Builder setSsidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        ssid_ = value;
        onChanged();
        return this;
      }

      // optional int32 status = 8;
      private int status_ ;
      /**
       * <code>optional int32 status = 8;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 status = 8;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>optional int32 status = 8;</code>
       */
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000080;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 status = 8;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000080);
        status_ = 0;
        onChanged();
        return this;
      }

      // optional int32 networkType = 9;
      private int networkType_ ;
      /**
       * <code>optional int32 networkType = 9;</code>
       */
      public boolean hasNetworkType() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int32 networkType = 9;</code>
       */
      public int getNetworkType() {
        return networkType_;
      }
      /**
       * <code>optional int32 networkType = 9;</code>
       */
      public Builder setNetworkType(int value) {
        bitField0_ |= 0x00000100;
        networkType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 networkType = 9;</code>
       */
      public Builder clearNetworkType() {
        bitField0_ = (bitField0_ & ~0x00000100);
        networkType_ = 0;
        onChanged();
        return this;
      }

      // optional string signature = 10;
      private java.lang.Object signature_ = "";
      /**
       * <code>optional string signature = 10;</code>
       */
      public boolean hasSignature() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string signature = 10;</code>
       */
      public java.lang.String getSignature() {
        java.lang.Object ref = signature_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          signature_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string signature = 10;</code>
       */
      public com.google.protobuf.ByteString
          getSignatureBytes() {
        java.lang.Object ref = signature_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          signature_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string signature = 10;</code>
       */
      public Builder setSignature(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string signature = 10;</code>
       */
      public Builder clearSignature() {
        bitField0_ = (bitField0_ & ~0x00000200);
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }
      /**
       * <code>optional string signature = 10;</code>
       */
      public Builder setSignatureBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        signature_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.zhaoyan.juyou.PBUserInfo)
    }

    static {
      defaultInstance = new PBUserInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.zhaoyan.juyou.PBUserInfo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zhaoyan_juyou_PBUserInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zhaoyan_juyou_PBUserInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017user_info.proto\022\021com.zhaoyan.juyou\"\301\001\n" +
      "\nPBUserInfo\022\016\n\006userId\030\001 \001(\005\022\020\n\010userName\030" +
      "\002 \001(\t\022\023\n\013headImageId\030\003 \001(\005\022\025\n\rheadImageD" +
      "ata\030\004 \001(\014\022\021\n\tipAddress\030\005 \001(\t\022\014\n\004type\030\006 \001" +
      "(\005\022\014\n\004ssid\030\007 \001(\t\022\016\n\006status\030\010 \001(\005\022\023\n\013netw" +
      "orkType\030\t \001(\005\022\021\n\tsignature\030\n \001(\tB9\n%com." +
      "zhaoyan.communication.protocol.pbB\020PBUse" +
      "rInfoProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_zhaoyan_juyou_PBUserInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_zhaoyan_juyou_PBUserInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_zhaoyan_juyou_PBUserInfo_descriptor,
              new java.lang.String[] { "UserId", "UserName", "HeadImageId", "HeadImageData", "IpAddress", "Type", "Ssid", "Status", "NetworkType", "Signature", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
