// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_update.proto

package com.zhaoyan.communication.protocol.pb;

public final class PBUserUpdateProtos {
  private PBUserUpdateProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PBUpdateUserIdOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated int32 userId = 1;
    /**
     * <code>repeated int32 userId = 1;</code>
     */
    java.util.List<java.lang.Integer> getUserIdList();
    /**
     * <code>repeated int32 userId = 1;</code>
     */
    int getUserIdCount();
    /**
     * <code>repeated int32 userId = 1;</code>
     */
    int getUserId(int index);
  }
  /**
   * Protobuf type {@code com.zhaoyan.juyou.PBUpdateUserId}
   */
  public static final class PBUpdateUserId extends
      com.google.protobuf.GeneratedMessage
      implements PBUpdateUserIdOrBuilder {
    // Use PBUpdateUserId.newBuilder() to construct.
    private PBUpdateUserId(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PBUpdateUserId(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PBUpdateUserId defaultInstance;
    public static PBUpdateUserId getDefaultInstance() {
      return defaultInstance;
    }

    public PBUpdateUserId getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PBUpdateUserId(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                userId_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              userId_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                userId_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                userId_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          userId_ = java.util.Collections.unmodifiableList(userId_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.internal_static_com_zhaoyan_juyou_PBUpdateUserId_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.internal_static_com_zhaoyan_juyou_PBUpdateUserId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserId.class, com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserId.Builder.class);
    }

    public static com.google.protobuf.Parser<PBUpdateUserId> PARSER =
        new com.google.protobuf.AbstractParser<PBUpdateUserId>() {
      public PBUpdateUserId parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBUpdateUserId(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PBUpdateUserId> getParserForType() {
      return PARSER;
    }

    // repeated int32 userId = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> userId_;
    /**
     * <code>repeated int32 userId = 1;</code>
     */
    public java.util.List<java.lang.Integer>
        getUserIdList() {
      return userId_;
    }
    /**
     * <code>repeated int32 userId = 1;</code>
     */
    public int getUserIdCount() {
      return userId_.size();
    }
    /**
     * <code>repeated int32 userId = 1;</code>
     */
    public int getUserId(int index) {
      return userId_.get(index);
    }

    private void initFields() {
      userId_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < userId_.size(); i++) {
        output.writeInt32(1, userId_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < userId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(userId_.get(i));
        }
        size += dataSize;
        size += 1 * getUserIdList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserId parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserId parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserId parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserId parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserId parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserId parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserId parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserId parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserId parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserId parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserId prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zhaoyan.juyou.PBUpdateUserId}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserIdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.internal_static_com_zhaoyan_juyou_PBUpdateUserId_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.internal_static_com_zhaoyan_juyou_PBUpdateUserId_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserId.class, com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserId.Builder.class);
      }

      // Construct using com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserId.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.internal_static_com_zhaoyan_juyou_PBUpdateUserId_descriptor;
      }

      public com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserId getDefaultInstanceForType() {
        return com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserId.getDefaultInstance();
      }

      public com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserId build() {
        com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserId result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserId buildPartial() {
        com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserId result = new com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserId(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          userId_ = java.util.Collections.unmodifiableList(userId_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.userId_ = userId_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserId) {
          return mergeFrom((com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserId)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserId other) {
        if (other == com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserId.getDefaultInstance()) return this;
        if (!other.userId_.isEmpty()) {
          if (userId_.isEmpty()) {
            userId_ = other.userId_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUserIdIsMutable();
            userId_.addAll(other.userId_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserId parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserId) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated int32 userId = 1;
      private java.util.List<java.lang.Integer> userId_ = java.util.Collections.emptyList();
      private void ensureUserIdIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          userId_ = new java.util.ArrayList<java.lang.Integer>(userId_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 userId = 1;</code>
       */
      public java.util.List<java.lang.Integer>
          getUserIdList() {
        return java.util.Collections.unmodifiableList(userId_);
      }
      /**
       * <code>repeated int32 userId = 1;</code>
       */
      public int getUserIdCount() {
        return userId_.size();
      }
      /**
       * <code>repeated int32 userId = 1;</code>
       */
      public int getUserId(int index) {
        return userId_.get(index);
      }
      /**
       * <code>repeated int32 userId = 1;</code>
       */
      public Builder setUserId(
          int index, int value) {
        ensureUserIdIsMutable();
        userId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 userId = 1;</code>
       */
      public Builder addUserId(int value) {
        ensureUserIdIsMutable();
        userId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 userId = 1;</code>
       */
      public Builder addAllUserId(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureUserIdIsMutable();
        super.addAll(values, userId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 userId = 1;</code>
       */
      public Builder clearUserId() {
        userId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.zhaoyan.juyou.PBUpdateUserId)
    }

    static {
      defaultInstance = new PBUpdateUserId(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.zhaoyan.juyou.PBUpdateUserId)
  }

  public interface PBUpdateUserInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.zhaoyan.juyou.PBUserInfo userInfo = 1;
    /**
     * <code>required .com.zhaoyan.juyou.PBUserInfo userInfo = 1;</code>
     */
    boolean hasUserInfo();
    /**
     * <code>required .com.zhaoyan.juyou.PBUserInfo userInfo = 1;</code>
     */
    com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo getUserInfo();
    /**
     * <code>required .com.zhaoyan.juyou.PBUserInfo userInfo = 1;</code>
     */
    com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfoOrBuilder getUserInfoOrBuilder();
  }
  /**
   * Protobuf type {@code com.zhaoyan.juyou.PBUpdateUserInfo}
   */
  public static final class PBUpdateUserInfo extends
      com.google.protobuf.GeneratedMessage
      implements PBUpdateUserInfoOrBuilder {
    // Use PBUpdateUserInfo.newBuilder() to construct.
    private PBUpdateUserInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PBUpdateUserInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PBUpdateUserInfo defaultInstance;
    public static PBUpdateUserInfo getDefaultInstance() {
      return defaultInstance;
    }

    public PBUpdateUserInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PBUpdateUserInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = userInfo_.toBuilder();
              }
              userInfo_ = input.readMessage(com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(userInfo_);
                userInfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.internal_static_com_zhaoyan_juyou_PBUpdateUserInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.internal_static_com_zhaoyan_juyou_PBUpdateUserInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserInfo.class, com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<PBUpdateUserInfo> PARSER =
        new com.google.protobuf.AbstractParser<PBUpdateUserInfo>() {
      public PBUpdateUserInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBUpdateUserInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PBUpdateUserInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .com.zhaoyan.juyou.PBUserInfo userInfo = 1;
    public static final int USERINFO_FIELD_NUMBER = 1;
    private com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo userInfo_;
    /**
     * <code>required .com.zhaoyan.juyou.PBUserInfo userInfo = 1;</code>
     */
    public boolean hasUserInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.zhaoyan.juyou.PBUserInfo userInfo = 1;</code>
     */
    public com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo getUserInfo() {
      return userInfo_;
    }
    /**
     * <code>required .com.zhaoyan.juyou.PBUserInfo userInfo = 1;</code>
     */
    public com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfoOrBuilder getUserInfoOrBuilder() {
      return userInfo_;
    }

    private void initFields() {
      userInfo_ = com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserInfo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, userInfo_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, userInfo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zhaoyan.juyou.PBUpdateUserInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.internal_static_com_zhaoyan_juyou_PBUpdateUserInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.internal_static_com_zhaoyan_juyou_PBUpdateUserInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserInfo.class, com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserInfo.Builder.class);
      }

      // Construct using com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUserInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (userInfoBuilder_ == null) {
          userInfo_ = com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo.getDefaultInstance();
        } else {
          userInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.internal_static_com_zhaoyan_juyou_PBUpdateUserInfo_descriptor;
      }

      public com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserInfo getDefaultInstanceForType() {
        return com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserInfo.getDefaultInstance();
      }

      public com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserInfo build() {
        com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserInfo buildPartial() {
        com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserInfo result = new com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (userInfoBuilder_ == null) {
          result.userInfo_ = userInfo_;
        } else {
          result.userInfo_ = userInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserInfo) {
          return mergeFrom((com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserInfo other) {
        if (other == com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserInfo.getDefaultInstance()) return this;
        if (other.hasUserInfo()) {
          mergeUserInfo(other.getUserInfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserInfo()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zhaoyan.communication.protocol.pb.PBUserUpdateProtos.PBUpdateUserInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.zhaoyan.juyou.PBUserInfo userInfo = 1;
      private com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo userInfo_ = com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo, com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo.Builder, com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfoOrBuilder> userInfoBuilder_;
      /**
       * <code>required .com.zhaoyan.juyou.PBUserInfo userInfo = 1;</code>
       */
      public boolean hasUserInfo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.zhaoyan.juyou.PBUserInfo userInfo = 1;</code>
       */
      public com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo getUserInfo() {
        if (userInfoBuilder_ == null) {
          return userInfo_;
        } else {
          return userInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.zhaoyan.juyou.PBUserInfo userInfo = 1;</code>
       */
      public Builder setUserInfo(com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo value) {
        if (userInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          userInfo_ = value;
          onChanged();
        } else {
          userInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.zhaoyan.juyou.PBUserInfo userInfo = 1;</code>
       */
      public Builder setUserInfo(
          com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo.Builder builderForValue) {
        if (userInfoBuilder_ == null) {
          userInfo_ = builderForValue.build();
          onChanged();
        } else {
          userInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.zhaoyan.juyou.PBUserInfo userInfo = 1;</code>
       */
      public Builder mergeUserInfo(com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo value) {
        if (userInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              userInfo_ != com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo.getDefaultInstance()) {
            userInfo_ =
              com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo.newBuilder(userInfo_).mergeFrom(value).buildPartial();
          } else {
            userInfo_ = value;
          }
          onChanged();
        } else {
          userInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.zhaoyan.juyou.PBUserInfo userInfo = 1;</code>
       */
      public Builder clearUserInfo() {
        if (userInfoBuilder_ == null) {
          userInfo_ = com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo.getDefaultInstance();
          onChanged();
        } else {
          userInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .com.zhaoyan.juyou.PBUserInfo userInfo = 1;</code>
       */
      public com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo.Builder getUserInfoBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getUserInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.zhaoyan.juyou.PBUserInfo userInfo = 1;</code>
       */
      public com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfoOrBuilder getUserInfoOrBuilder() {
        if (userInfoBuilder_ != null) {
          return userInfoBuilder_.getMessageOrBuilder();
        } else {
          return userInfo_;
        }
      }
      /**
       * <code>required .com.zhaoyan.juyou.PBUserInfo userInfo = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo, com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo.Builder, com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfoOrBuilder> 
          getUserInfoFieldBuilder() {
        if (userInfoBuilder_ == null) {
          userInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo, com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfo.Builder, com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.PBUserInfoOrBuilder>(
                  userInfo_,
                  getParentForChildren(),
                  isClean());
          userInfo_ = null;
        }
        return userInfoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.zhaoyan.juyou.PBUpdateUserInfo)
    }

    static {
      defaultInstance = new PBUpdateUserInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.zhaoyan.juyou.PBUpdateUserInfo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zhaoyan_juyou_PBUpdateUserId_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zhaoyan_juyou_PBUpdateUserId_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zhaoyan_juyou_PBUpdateUserInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zhaoyan_juyou_PBUpdateUserInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021user_update.proto\022\021com.zhaoyan.juyou\032\017" +
      "user_info.proto\" \n\016PBUpdateUserId\022\016\n\006use" +
      "rId\030\001 \003(\005\"C\n\020PBUpdateUserInfo\022/\n\010userInf" +
      "o\030\001 \002(\0132\035.com.zhaoyan.juyou.PBUserInfoB;" +
      "\n%com.zhaoyan.communication.protocol.pbB" +
      "\022PBUserUpdateProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_zhaoyan_juyou_PBUpdateUserId_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_zhaoyan_juyou_PBUpdateUserId_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_zhaoyan_juyou_PBUpdateUserId_descriptor,
              new java.lang.String[] { "UserId", });
          internal_static_com_zhaoyan_juyou_PBUpdateUserInfo_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_zhaoyan_juyou_PBUpdateUserInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_zhaoyan_juyou_PBUpdateUserInfo_descriptor,
              new java.lang.String[] { "UserInfo", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.zhaoyan.communication.protocol.pb.PBUserInfoProtos.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
