// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speak_game.proto

package com.zhaoyan.juyou.game.chengyudahui.protocol.pb;

public final class SpeakGameProtos {
  private SpeakGameProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SpeakGameMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.GameType game = 1 [default = SPEAK];
    /**
     * <code>required .com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.GameType game = 1 [default = SPEAK];</code>
     */
    boolean hasGame();
    /**
     * <code>required .com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.GameType game = 1 [default = SPEAK];</code>
     */
    com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.GameType getGame();

    // required .com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.Command command = 2 [default = START];
    /**
     * <code>required .com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.Command command = 2 [default = START];</code>
     */
    boolean hasCommand();
    /**
     * <code>required .com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.Command command = 2 [default = START];</code>
     */
    com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.Command getCommand();

    // optional int32 word = 3;
    /**
     * <code>optional int32 word = 3;</code>
     */
    boolean hasWord();
    /**
     * <code>optional int32 word = 3;</code>
     */
    int getWord();

    // optional int32 time = 4;
    /**
     * <code>optional int32 time = 4;</code>
     */
    boolean hasTime();
    /**
     * <code>optional int32 time = 4;</code>
     */
    int getTime();

    // optional .com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.RoleType type = 5 [default = UNKONWN];
    /**
     * <code>optional .com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.RoleType type = 5 [default = UNKONWN];</code>
     */
    boolean hasType();
    /**
     * <code>optional .com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.RoleType type = 5 [default = UNKONWN];</code>
     */
    com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.RoleType getType();
  }
  /**
   * Protobuf type {@code com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg}
   */
  public static final class SpeakGameMsg extends
      com.google.protobuf.GeneratedMessage
      implements SpeakGameMsgOrBuilder {
    // Use SpeakGameMsg.newBuilder() to construct.
    private SpeakGameMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SpeakGameMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SpeakGameMsg defaultInstance;
    public static SpeakGameMsg getDefaultInstance() {
      return defaultInstance;
    }

    public SpeakGameMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SpeakGameMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.GameType value = com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.GameType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                game_ = value;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.Command value = com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.Command.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                command_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              word_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              time_ = input.readInt32();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.RoleType value = com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.RoleType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                type_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.internal_static_com_zhaoyan_juyou_game_chengyudahui_SpeakGameMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.internal_static_com_zhaoyan_juyou_game_chengyudahui_SpeakGameMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.class, com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<SpeakGameMsg> PARSER =
        new com.google.protobuf.AbstractParser<SpeakGameMsg>() {
      public SpeakGameMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SpeakGameMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SpeakGameMsg> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.Command}
     */
    public enum Command
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>START = 1;</code>
       */
      START(0, 1),
      /**
       * <code>READY = 2;</code>
       */
      READY(1, 2),
      /**
       * <code>MSG = 3;</code>
       */
      MSG(2, 3),
      /**
       * <code>NEXT = 4;</code>
       */
      NEXT(3, 4),
      /**
       * <code>ROLE = 5;</code>
       */
      ROLE(4, 5),
      /**
       * <code>GAMESTART = 6;</code>
       */
      GAMESTART(5, 6),
      /**
       * <code>ROLYEREADY = 7;</code>
       */
      ROLYEREADY(6, 7),
      /**
       * <code>SCORE = 8;</code>
       */
      SCORE(7, 8),
      /**
       * <code>TIME = 9;</code>
       */
      TIME(8, 9),
      ;

      /**
       * <code>START = 1;</code>
       */
      public static final int START_VALUE = 1;
      /**
       * <code>READY = 2;</code>
       */
      public static final int READY_VALUE = 2;
      /**
       * <code>MSG = 3;</code>
       */
      public static final int MSG_VALUE = 3;
      /**
       * <code>NEXT = 4;</code>
       */
      public static final int NEXT_VALUE = 4;
      /**
       * <code>ROLE = 5;</code>
       */
      public static final int ROLE_VALUE = 5;
      /**
       * <code>GAMESTART = 6;</code>
       */
      public static final int GAMESTART_VALUE = 6;
      /**
       * <code>ROLYEREADY = 7;</code>
       */
      public static final int ROLYEREADY_VALUE = 7;
      /**
       * <code>SCORE = 8;</code>
       */
      public static final int SCORE_VALUE = 8;
      /**
       * <code>TIME = 9;</code>
       */
      public static final int TIME_VALUE = 9;


      public final int getNumber() { return value; }

      public static Command valueOf(int value) {
        switch (value) {
          case 1: return START;
          case 2: return READY;
          case 3: return MSG;
          case 4: return NEXT;
          case 5: return ROLE;
          case 6: return GAMESTART;
          case 7: return ROLYEREADY;
          case 8: return SCORE;
          case 9: return TIME;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Command>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Command>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Command>() {
              public Command findValueByNumber(int number) {
                return Command.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.getDescriptor().getEnumTypes().get(0);
      }

      private static final Command[] VALUES = values();

      public static Command valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Command(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.Command)
    }

    /**
     * Protobuf enum {@code com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.RoleType}
     */
    public enum RoleType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>REFEREE = 1;</code>
       */
      REFEREE(0, 1),
      /**
       * <code>ACTOR = 2;</code>
       */
      ACTOR(1, 2),
      /**
       * <code>OBSERVER = 3;</code>
       */
      OBSERVER(2, 3),
      /**
       * <code>UNKONWN = 4;</code>
       */
      UNKONWN(3, 4),
      ;

      /**
       * <code>REFEREE = 1;</code>
       */
      public static final int REFEREE_VALUE = 1;
      /**
       * <code>ACTOR = 2;</code>
       */
      public static final int ACTOR_VALUE = 2;
      /**
       * <code>OBSERVER = 3;</code>
       */
      public static final int OBSERVER_VALUE = 3;
      /**
       * <code>UNKONWN = 4;</code>
       */
      public static final int UNKONWN_VALUE = 4;


      public final int getNumber() { return value; }

      public static RoleType valueOf(int value) {
        switch (value) {
          case 1: return REFEREE;
          case 2: return ACTOR;
          case 3: return OBSERVER;
          case 4: return UNKONWN;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<RoleType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<RoleType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<RoleType>() {
              public RoleType findValueByNumber(int number) {
                return RoleType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.getDescriptor().getEnumTypes().get(1);
      }

      private static final RoleType[] VALUES = values();

      public static RoleType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private RoleType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.RoleType)
    }

    /**
     * Protobuf enum {@code com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.GameType}
     */
    public enum GameType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SPEAK = 1;</code>
       */
      SPEAK(0, 1),
      /**
       * <code>PAINT = 2;</code>
       */
      PAINT(1, 2),
      ;

      /**
       * <code>SPEAK = 1;</code>
       */
      public static final int SPEAK_VALUE = 1;
      /**
       * <code>PAINT = 2;</code>
       */
      public static final int PAINT_VALUE = 2;


      public final int getNumber() { return value; }

      public static GameType valueOf(int value) {
        switch (value) {
          case 1: return SPEAK;
          case 2: return PAINT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<GameType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<GameType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<GameType>() {
              public GameType findValueByNumber(int number) {
                return GameType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.getDescriptor().getEnumTypes().get(2);
      }

      private static final GameType[] VALUES = values();

      public static GameType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private GameType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.GameType)
    }

    private int bitField0_;
    // required .com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.GameType game = 1 [default = SPEAK];
    public static final int GAME_FIELD_NUMBER = 1;
    private com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.GameType game_;
    /**
     * <code>required .com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.GameType game = 1 [default = SPEAK];</code>
     */
    public boolean hasGame() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.GameType game = 1 [default = SPEAK];</code>
     */
    public com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.GameType getGame() {
      return game_;
    }

    // required .com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.Command command = 2 [default = START];
    public static final int COMMAND_FIELD_NUMBER = 2;
    private com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.Command command_;
    /**
     * <code>required .com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.Command command = 2 [default = START];</code>
     */
    public boolean hasCommand() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.Command command = 2 [default = START];</code>
     */
    public com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.Command getCommand() {
      return command_;
    }

    // optional int32 word = 3;
    public static final int WORD_FIELD_NUMBER = 3;
    private int word_;
    /**
     * <code>optional int32 word = 3;</code>
     */
    public boolean hasWord() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 word = 3;</code>
     */
    public int getWord() {
      return word_;
    }

    // optional int32 time = 4;
    public static final int TIME_FIELD_NUMBER = 4;
    private int time_;
    /**
     * <code>optional int32 time = 4;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 time = 4;</code>
     */
    public int getTime() {
      return time_;
    }

    // optional .com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.RoleType type = 5 [default = UNKONWN];
    public static final int TYPE_FIELD_NUMBER = 5;
    private com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.RoleType type_;
    /**
     * <code>optional .com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.RoleType type = 5 [default = UNKONWN];</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.RoleType type = 5 [default = UNKONWN];</code>
     */
    public com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.RoleType getType() {
      return type_;
    }

    private void initFields() {
      game_ = com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.GameType.SPEAK;
      command_ = com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.Command.START;
      word_ = 0;
      time_ = 0;
      type_ = com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.RoleType.UNKONWN;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasGame()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCommand()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, game_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, command_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, word_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, time_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, type_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, game_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, command_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, word_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, time_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, type_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.internal_static_com_zhaoyan_juyou_game_chengyudahui_SpeakGameMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.internal_static_com_zhaoyan_juyou_game_chengyudahui_SpeakGameMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.class, com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.Builder.class);
      }

      // Construct using com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        game_ = com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.GameType.SPEAK;
        bitField0_ = (bitField0_ & ~0x00000001);
        command_ = com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.Command.START;
        bitField0_ = (bitField0_ & ~0x00000002);
        word_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        time_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.RoleType.UNKONWN;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.internal_static_com_zhaoyan_juyou_game_chengyudahui_SpeakGameMsg_descriptor;
      }

      public com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg getDefaultInstanceForType() {
        return com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.getDefaultInstance();
      }

      public com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg build() {
        com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg buildPartial() {
        com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg result = new com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.game_ = game_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.command_ = command_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.word_ = word_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg) {
          return mergeFrom((com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg other) {
        if (other == com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.getDefaultInstance()) return this;
        if (other.hasGame()) {
          setGame(other.getGame());
        }
        if (other.hasCommand()) {
          setCommand(other.getCommand());
        }
        if (other.hasWord()) {
          setWord(other.getWord());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasGame()) {
          
          return false;
        }
        if (!hasCommand()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.GameType game = 1 [default = SPEAK];
      private com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.GameType game_ = com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.GameType.SPEAK;
      /**
       * <code>required .com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.GameType game = 1 [default = SPEAK];</code>
       */
      public boolean hasGame() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.GameType game = 1 [default = SPEAK];</code>
       */
      public com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.GameType getGame() {
        return game_;
      }
      /**
       * <code>required .com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.GameType game = 1 [default = SPEAK];</code>
       */
      public Builder setGame(com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.GameType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        game_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.GameType game = 1 [default = SPEAK];</code>
       */
      public Builder clearGame() {
        bitField0_ = (bitField0_ & ~0x00000001);
        game_ = com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.GameType.SPEAK;
        onChanged();
        return this;
      }

      // required .com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.Command command = 2 [default = START];
      private com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.Command command_ = com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.Command.START;
      /**
       * <code>required .com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.Command command = 2 [default = START];</code>
       */
      public boolean hasCommand() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.Command command = 2 [default = START];</code>
       */
      public com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.Command getCommand() {
        return command_;
      }
      /**
       * <code>required .com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.Command command = 2 [default = START];</code>
       */
      public Builder setCommand(com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.Command value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        command_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.Command command = 2 [default = START];</code>
       */
      public Builder clearCommand() {
        bitField0_ = (bitField0_ & ~0x00000002);
        command_ = com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.Command.START;
        onChanged();
        return this;
      }

      // optional int32 word = 3;
      private int word_ ;
      /**
       * <code>optional int32 word = 3;</code>
       */
      public boolean hasWord() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 word = 3;</code>
       */
      public int getWord() {
        return word_;
      }
      /**
       * <code>optional int32 word = 3;</code>
       */
      public Builder setWord(int value) {
        bitField0_ |= 0x00000004;
        word_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 word = 3;</code>
       */
      public Builder clearWord() {
        bitField0_ = (bitField0_ & ~0x00000004);
        word_ = 0;
        onChanged();
        return this;
      }

      // optional int32 time = 4;
      private int time_ ;
      /**
       * <code>optional int32 time = 4;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 time = 4;</code>
       */
      public int getTime() {
        return time_;
      }
      /**
       * <code>optional int32 time = 4;</code>
       */
      public Builder setTime(int value) {
        bitField0_ |= 0x00000008;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 time = 4;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        time_ = 0;
        onChanged();
        return this;
      }

      // optional .com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.RoleType type = 5 [default = UNKONWN];
      private com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.RoleType type_ = com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.RoleType.UNKONWN;
      /**
       * <code>optional .com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.RoleType type = 5 [default = UNKONWN];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.RoleType type = 5 [default = UNKONWN];</code>
       */
      public com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.RoleType getType() {
        return type_;
      }
      /**
       * <code>optional .com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.RoleType type = 5 [default = UNKONWN];</code>
       */
      public Builder setType(com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.RoleType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg.RoleType type = 5 [default = UNKONWN];</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        type_ = com.zhaoyan.juyou.game.chengyudahui.protocol.pb.SpeakGameProtos.SpeakGameMsg.RoleType.UNKONWN;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg)
    }

    static {
      defaultInstance = new SpeakGameMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.zhaoyan.juyou.game.chengyudahui.SpeakGameMsg)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zhaoyan_juyou_game_chengyudahui_SpeakGameMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zhaoyan_juyou_game_chengyudahui_SpeakGameMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020speak_game.proto\022#com.zhaoyan.juyou.ga" +
      "me.chengyudahui\"\364\003\n\014SpeakGameMsg\022O\n\004game" +
      "\030\001 \002(\0162:.com.zhaoyan.juyou.game.chengyud" +
      "ahui.SpeakGameMsg.GameType:\005SPEAK\022Q\n\007com" +
      "mand\030\002 \002(\01629.com.zhaoyan.juyou.game.chen" +
      "gyudahui.SpeakGameMsg.Command:\005START\022\014\n\004" +
      "word\030\003 \001(\005\022\014\n\004time\030\004 \001(\005\022Q\n\004type\030\005 \001(\0162:" +
      ".com.zhaoyan.juyou.game.chengyudahui.Spe" +
      "akGameMsg.RoleType:\007UNKONWN\"p\n\007Command\022\t" +
      "\n\005START\020\001\022\t\n\005READY\020\002\022\007\n\003MSG\020\003\022\010\n\004NEXT\020\004\022",
      "\010\n\004ROLE\020\005\022\r\n\tGAMESTART\020\006\022\016\n\nROLYEREADY\020\007" +
      "\022\t\n\005SCORE\020\010\022\010\n\004TIME\020\t\"=\n\010RoleType\022\013\n\007REF" +
      "EREE\020\001\022\t\n\005ACTOR\020\002\022\014\n\010OBSERVER\020\003\022\013\n\007UNKON" +
      "WN\020\004\" \n\010GameType\022\t\n\005SPEAK\020\001\022\t\n\005PAINT\020\002BB" +
      "\n/com.zhaoyan.juyou.game.chengyudahui.pr" +
      "otocol.pbB\017SpeakGameProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_zhaoyan_juyou_game_chengyudahui_SpeakGameMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_zhaoyan_juyou_game_chengyudahui_SpeakGameMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_zhaoyan_juyou_game_chengyudahui_SpeakGameMsg_descriptor,
              new java.lang.String[] { "Game", "Command", "Word", "Time", "Type", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
